epam/UUI

draft-rte/src/common/Toolbar/buttons/ImageButton.tsx, draft-rte/src/common/Toolbar/buttons/LinkButton.tsx, epam-promo/components/pickers/PickerInput.tsx, epam-promo/components/tables/DataTable.tsx, epam-promo/docs/contexts/ModalContext.tsx, loveship/components/pickers/PickerInput.tsx, loveship/components/pickers/PickerList.tsx, loveship/components/tables/DataTable.tsx, loveship/docs/contexts/ModalContext.tsx, uui-editor/src/plugins/imagePlugin/imagePlugin.tsx, uui-editor/src/plugins/linkPlugin/linkPlugin.tsx, uui-editor/src/plugins/videoPlugin/videoPlugin.tsx
Added handling of unhandled rejection warnings to 'draft-rte', 'promo', 'loveship' and 'uui-editor' packages
=> Added handling of unhandled rejection warnings

app/src/docs/VirtualList.doc.tsx, app/src/docs/examples/virtualList/Basic.example.tsx, app/src/docs/examples/virtualList/BasicExample.scss, app/src/docs/index.ts, app/src/documents/structure.ts, epam-promo/components/layout/__tests__/__snapshots__/VirtualList.test.tsx.snap, epam-promo/components/pickers/__tests__/__snapshots__/DataPickerBody.test.tsx.snap, epam-promo/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, epam-promo/components/tables/__tests__/__snapshots__/ColumnPickerFilter.test.tsx.snap, epam-promo/components/tables/__tests__/__snapshots__/DataTable.test.tsx.snap, loveship/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/ColumnPickerFilter.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/DataTable.test.tsx.snap, public/docs/content/examples-virtualList-Basic.json, public/docs/content/virtual-list-descriptions.json, uui-components/src/layout/VirtualList.scss, uui-components/src/layout/VirtualList.tsx
Fix for: https://github.com/epam/UUI/issues/40
=> VirtualList - docs, dynamic height issue fix

epam-promo/components/buttons/LinkButton.scss
=> [LinkButton]: fix hover styles for disabled button

readme.md
Updated Readme.md with steps to run the App locally.
=> docs: To start locally update

uui-components/src/pickers/PickerInputBase.tsx
=> [PickerInput]: fix clear icon in input when searchPosition is 'body'

uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerToggler.tsx
=> [PickerInput]: fix pass onFocus and onBlur in props

epam-promo/components/typography/TextPlaceholder.scss, epam-promo/components/typography/TextPlaceholder.tsx, epam-promo/components/typography/__tests__/__snapshots__/TextPlaceholder.test.tsx.snap, epam-promo/components/typography/docs/textPlaceholder.doc.tsx, loveship/components/typography/TextPlaceholder.scss, loveship/components/typography/TextPlaceholder.tsx, loveship/components/typography/__tests__/__snapshots__/TextPlaceholder.test.tsx.snap, loveship/components/typography/docs/textPlaceholder.doc.tsx
=> [TextPlacehoder]: fix displaying 0000 if the font is not loaded yet

loveship/components/tables/ColumnsConfigurationModal.tsx, loveship/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap
=> [DataTable]: add 'Reset to default' button in ColumnsConfigurationModal for the loveship

epam-promo/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, loveship/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerToggler.tsx
=> [PickerInput]: fix close portal with list clicking on PickerInput

app/src/docs/NumericInput.doc.tsx, app/src/docs/examples/numericInput/Formatter.example.tsx, epam-promo/components/inputs/docs/numericInput.doc.ts, loveship/components/inputs/docs/numericInput.doc.ts, public/docs/componentsPropsSet.json, public/docs/content/examples-numericInput-Formatter.json, uui-components/src/inputs/NumericInput.tsx, uui-docs/src/commonDocs/commonDocs.tsx, uui/types/props.ts
=> [NumericInput]: feat: add possibility to pass formatter in props

changelog.md
=> docs: edit changelog

changelog.md, loveship/components/buttons/Button.scss
fix possibility to selecting caption value
=> [Button]: fix possibility to selecting caption value

uui-components/src/inputs/NumericInput.tsx, uui/helpers/__tests__/numericInputCalculations.test.tsx, uui/helpers/numericInputCalculations.ts
Fix calculation of floating-point numbers after clicking increase and decrease buttons
=> [NumericInput]: fix calculation of floating-point numbers

uui-components/src/inputs/NumericInput.tsx, uui/helpers/index.ts
Fix incorrect path for import getCalculatedValue in NumericInput
=> [NumericInput] fix: import path to getCalculatedValue

app/src/docs/examples/richTextView/Basic.example.tsx, epam-assets/scss/promo/typography.scss, epam-assets/scss/typography.scss, epam-promo/assets/styles/typography.scss, loveship/assets/styles/scss/typography.scss
fix global margin and padding for tags and elements
=> [Typography]: fix global margin and padding for tags and elements

readme.md
This PR adds a codesandbox link to UUI main README.md file
=> feat: created a template for codesandbox (issue #87)

app/package.json, app/src/analyticsEvents/index.ts, app/src/analyticsEvents/listeners/AmplitudeListener.ts, app/src/analyticsEvents/listeners/index.ts, app/src/docs/examples/contexts/AnalyticsContextBase.example.tsx, app/src/docs/examples/contexts/ContextProvider.example.tsx, app/src/index.tsx, uui/package.json, uui/services/AnalyticsContext.ts, uui/services/ApiContext.ts, uui/services/ContextProvider.tsx, uui/services/LegacyContextProvider.tsx, uui/services/analytics/GAListener.ts, uui/types/contexts.ts
[ContextProvider]: refactor implementation of Google Analytics in AnalyticsContext and remove loadAppContext from LegacyContextProvider
=> [ContextProvider]: refactor ContextProvider

app/src/docs/DropdownMenu.doc.tsx, app/src/docs/examples/dropdownMenu/Basic.example.tsx, app/src/docs/index.ts, app/src/documents/structure.ts, epam-promo/components/inputs/Switch.scss, epam-promo/components/overlays/DropdownContainer.scss, epam-promo/components/overlays/DropdownMenu.scss, epam-promo/components/overlays/DropdownMenu.tsx, epam-promo/components/overlays/index.tsx, public/docs/content/dropdown-descriptions.json, public/docs/content/dropdownMenu-descriptions.json, public/docs/content/examples-dropdownMenu-Basic.json, uui-components/src/overlays/DropdownContainer.tsx
=> [WIP]:[DropdownMenu] implement DropdownMenu component

loveship/components/widgets/Badge.scss
=> [Badge]: fix cursor pointer if badge is clickable

changelog.md, epam-promo/components/pickers/PickerItem.scss, epam-promo/components/pickers/PickerItem.tsx, loveship/components/pickers/PickerItem.scss, loveship/components/pickers/PickerItem.tsx
=> [PickerInput]: fix padding for picker input

changelog.md
=> [Docs]: fix changelog

epam-promo/components/navigation/MainMenu/MainMenuSearch.tsx, epam-promo/components/navigation/MainMenu/__tests__/__snapshots__/MainMenuSearch.test.tsx.snap, loveship/components/navigation/MainMenu/MainMenuSearch.tsx, loveship/components/navigation/MainMenu/__tests__/__snapshots__/MainMenuSearch.test.tsx.snap
=> [MainMenuSearch]: fix passing 'onAccept' prop from MainMenuSearch to TextInput

uui-components/src/inputs/RadioInput.tsx, uui-components/src/layout/CheckboxGroup.scss, uui-components/src/layout/CheckboxGroup.tsx, uui-components/src/layout/ControlGroup.tsx, uui-components/src/layout/RadioGroup.scss, uui-components/src/layout/RadioGroup.tsx
As part of #104 (Control groups)
=> [CONTROL GROUPS]: Checkbox Groups, Radio Groups, Control Groups accessibility

epam-promo/components/buttons/Button.scss, epam-promo/components/buttons/IconButton.scss, epam-promo/components/buttons/LinkButton.scss, epam-promo/components/buttons/TabButton.scss, loveship/components/buttons/Button.scss, loveship/components/buttons/IconButton.scss, loveship/components/buttons/LinkButton.scss, loveship/components/buttons/TabButton.scss, uui-components/src/buttons/ButtonBase.tsx, uui-components/src/navigation/Anchor.tsx
As a part of #104 (Buttons and Links point)
=> [BUTTONS FOCUS]: Fix focus on all different buttons and links

uui-components/src/overlays/Dropdown.tsx
As a part of #104 (Dropdown point)
=> [DROPDOWN]: A11y parameters for Dropdown component

uui-components/src/overlays/ModalWindow.tsx
=> [MODALS]: Added aria-* attributes for modals

epam-promo/components/navigation/MainMenu/Burger/BurgerButton.tsx, epam-promo/components/navigation/MainMenu/GlobalMenu.tsx, epam-promo/components/navigation/MainMenu/MainMenuButton.tsx, uui-components/src/navigation/MainMenu/MainMenu.tsx, uui-components/src/navigation/MainMenu/MainMenuLogo.tsx
As a part of #104 (Main Menu point)
=> [MainMenu]: Aria-* attributes for main menu component

uui-components/src/layout/VirtualList.tsx
As a part of #104 (Virtual List point)
=> [VirtualList]: Virtual list a11y attributes

uui-components/src/overlays/Tooltip.tsx
=> [Tooltip]: Tooltip aria-* attributes

uui-components/src/inputs/Slider/Slider.tsx, uui-components/src/inputs/Slider/SliderBase.scss, uui-components/src/inputs/Slider/SliderHandle.tsx
=> [Slider]: Slider a11y attributes and value change on left-right key press

epam-promo/components/widgets/AvatarStack.tsx, loveship/components/widgets/AvatarStack.tsx
As a part of #104 (Avatar Stack)
=> [AvatarStack]: Avatar stack aria-* attributes

epam-promo/components/typography/TextPlaceholder.tsx, loveship/components/typography/TextPlaceholder.tsx
As a part of #104 (Text Placeholder)
=> [Text Placeholder]: Aria-* for text placeholder

epam-promo/components/tables/DataTable.tsx, epam-promo/package.json, loveship/components/tables/DataTable.tsx, loveship/package.json, uui-components/package.json, uui-components/src/layout/ScrollBars.tsx, uui-components/src/layout/VirtualList.tsx, uui-components/src/table/DataTableScrollRow.tsx, yarn.lock
=> [VirtualList]: replace legacy react-custom-scrollbars by react-custom-scrollbars-2

epam-promo/assets/styles/colorvars/layout/accordion-colorvars.scss, epam-promo/components/layout/Accordion.scss, uui-components/src/layout/Accordion.tsx
=> [Accordion]: A11y Accordion

epam-promo/assets/styles/controlColors.scss, epam-promo/components/buttons/Button.scss, epam-promo/components/buttons/IconButton.scss, epam-promo/components/buttons/LinkButton.scss, epam-promo/components/buttons/TabButton.scss, epam-promo/components/fileUpload/__tests__/__snapshots__/DropSpot.test.tsx.snap, epam-promo/components/fileUpload/__tests__/__snapshots__/FileCard.test.tsx.snap, epam-promo/components/inputs/Checkbox.scss, epam-promo/components/inputs/RadioInput.scss, epam-promo/components/inputs/Rating.scss, epam-promo/components/inputs/Rating.tsx, epam-promo/components/inputs/__tests__/__snapshots__/Rating.test.tsx.snap, epam-promo/components/layout/Accordion.scss, epam-promo/components/layout/IconContainer.scss, epam-promo/components/layout/IconContainer.tsx, epam-promo/components/layout/__tests__/__snapshots__/IconContainer.test.tsx.snap, epam-promo/components/widgets/AvatarStack.scss, epam-promo/components/widgets/AvatarStack.tsx, epam-promo/components/widgets/__tests__/__snapshots__/AvatarStack.test.tsx.snap
=> [Promo Button]: Implement new focus

epam-promo/components/inputs/Switch.scss, epam-promo/components/inputs/__tests__/__snapshots__/Switch.test.tsx.snap, loveship/components/inputs/Switch.scss, loveship/components/inputs/__tests__/__snapshots__/Switch.test.tsx.snap, uui-components/src/inputs/Switch.scss, uui-components/src/inputs/Switch.tsx
=> [Switch]: Refactor switch component to be accessible

epam-promo/components/pickers/DataPickerRow.tsx, epam-promo/components/tables/DataTableCell.tsx, epam-promo/components/tables/__tests__/__snapshots__/DataTableRow.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/DataTableRow.test.tsx.snap, uui-components/src/layout/VirtualList.scss, uui-components/src/layout/VirtualList.tsx, uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerToggler.tsx, uui-components/src/table/DataTableRow.tsx
As a part of #104 (Picker Input)
=> [Picker Input]: Picker input accessibility

epam-promo/components/widgets/Paginator.tsx, epam-promo/components/widgets/__tests__/__snapshots__/Paginator.test.tsx.snap, loveship/components/buttons/TabButton.tsx, loveship/components/widgets/Paginator.tsx, loveship/components/widgets/__tests__/__snapshots__/Paginator.test.tsx.snap, uui-components/src/widgets/Paginator.tsx
=> [Paginator]: Aria-* and keyboard support for Paginator component

epam-promo/components/inputs/Checkbox.scss, epam-promo/components/inputs/RadioInput.scss, epam-promo/components/inputs/Switch.scss, epam-promo/components/inputs/__tests__/__snapshots__/Checkbox.test.tsx.snap, epam-promo/components/inputs/__tests__/__snapshots__/RadioInput.test.tsx.snap, epam-promo/components/inputs/index.tsx, loveship/components/inputs/Checkbox.scss, loveship/components/inputs/RadioInput.scss, loveship/components/inputs/Switch.scss, loveship/components/inputs/__tests__/__snapshots__/Checkbox.test.tsx.snap, loveship/components/inputs/__tests__/__snapshots__/RadioInput.test.tsx.snap, uui-components/src/inputs/Checkbox.scss, uui-components/src/inputs/Checkbox.tsx, uui-components/src/inputs/RadioInput.scss, uui-components/src/inputs/RadioInput.tsx, uui-components/src/inputs/Switch.scss, uui-components/src/inputs/Switch.tsx, uui/types/components/Checkbox.ts
As a part of #104 (Radio Input, Checkboxes)
=> [RadioInput, Checkbox]: Refactor radio input and checkboxes

epam-promo/components/inputs/MultiSwitch.tsx, epam-promo/components/inputs/__tests__/__snapshots__/MultiSwitch.test.tsx.snap, loveship/components/inputs/MultiSwitch.tsx, loveship/components/inputs/__tests__/__snapshots__/MultiSwitch.test.tsx.snap
=> [Multiswitch]: Aria-* attributes

epam-promo/components/inputs/__tests__/__snapshots__/Rating.test.tsx.snap, epam-promo/components/inputs/index.tsx, loveship/components/inputs/__tests__/__snapshots__/Rating.test.tsx.snap, uui-components/src/inputs/Rating/BaseRating.tsx, uui-components/src/inputs/Slider/Slider.tsx
As a part of #104 (Slider Rating)
=> [Slider Rating]: Slider rating a11y

loveship/components/inputs/Slider/__tests__/__snapshots__/RangeSlider.test.tsx.snap, uui-components/src/inputs/Slider/RangeSlider.tsx, uui-components/src/inputs/Slider/SliderHandle.tsx
As a part of #104 (Range Slider)
=> [RangeSlider]: Keyboard support for Range Slider component

epam-promo/components/pickers/DataPickerRow.tsx
Fix double check after click on checkbox in row
=> [PickerInput]: fix double check after click on checkbox in row

app/src/docs/AvatarStack.doc.tsx, app/src/docs/examples/avatarStack/BasicExample.scss, app/src/docs/examples/avatarStack/RenderItem.example.tsx, epam-promo/components/widgets/AvatarStack.scss, epam-promo/components/widgets/AvatarStack.tsx, epam-promo/components/widgets/__tests__/__snapshots__/AvatarStack.test.tsx.snap, epam-promo/components/widgets/docs/avatarStack.doc.tsx, loveship/components/widgets/AvatarStack.scss, loveship/components/widgets/AvatarStack.tsx, loveship/components/widgets/__tests__/__snapshots__/AvatarStack.test.tsx.snap, loveship/components/widgets/docs/avatarStack.doc.tsx, public/docs/content/examples-avatarStack-RenderItem.json, uui-components/src/widgets/AvatarStack.scss, uui-components/src/widgets/AvatarStack.tsx, uui-components/src/widgets/index.ts
=> [AvatarStack]: add possibility render custom avatar by the prop renderItem

epam-promo/components/overlays/__tests__/DropdownMenu.test.tsx, epam-promo/components/overlays/__tests__/__snapshots__/DropdownMenu.test.tsx.snap
=> [DropdownMenu]: add tests

changelog.md, uui-components/src/inputs/TextArea.tsx
=> [TextArea]: fix scrolling jump after typing when received autosize prop

app/src/docs/assets/Downloads.doc.tsx
=> [Assets]: fix links for downloads UUI Libraries

epam-promo/components/layout/__tests__/__snapshots__/LabeledInput.test.tsx.snap, loveship/components/layout/__tests__/__snapshots__/LabeledInput.test.tsx.snap, uui-components/src/layout/LabeledInput.tsx
As a part of #104 (Labeled Input)
=> [LabeledInput]: A11y fix redundant role

epam-promo/components/overlays/__tests__/__snapshots__/ConfirmationModal.test.tsx.snap, epam-promo/components/overlays/__tests__/__snapshots__/Modals.test.tsx.snap, epam-promo/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, epam-promo/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, loveship/components/overlays/__tests__/__snapshots__/ConfirmationModal.test.tsx.snap, loveship/components/overlays/__tests__/__snapshots__/Modals.test.tsx.snap, loveship/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, uui-components/package.json, uui-components/src/overlays/ModalBlocker.tsx, yarn.lock
=> [Modals]: Focus lock for modal windows

readme.md
ref: https://gist.github.com/lifeart/43ade02d32806b96a9da45dcf62be0ef
=> EPAM OSS: Readme update initiative

epam-promo/components/inputs/RadioInput.scss, loveship/components/inputs/Checkbox.scss
=> [Checkbox & RadioInput]: fix applying color for invalid inputs.

epam-promo/components/navigation/MainMenu/MainMenuSearch.tsx, loveship/components/navigation/MainMenu/MainMenuSearch.tsx
=> [MainMenuSearch]: fix cx overwrite by cx from props

epam-promo/components/overlays/__tests__/__snapshots__/DropdownMenu.test.tsx.snap, uui-components/src/overlays/DropdownContainer.tsx
=> [DropdownMenu]: fix pass props style from DropdownMenuContainer to VPanel style

epam-promo/components/widgets/__tests__/IndeterminateBar.test.tsx, epam-promo/components/widgets/__tests__/IndicatorBar.test.tsx, epam-promo/components/widgets/__tests__/ProgressBar.test.tsx, epam-promo/components/widgets/__tests__/__snapshots__/IndeterminateBar.test.tsx.snap, epam-promo/components/widgets/__tests__/__snapshots__/IndicatorBar.test.tsx.snap, epam-promo/components/widgets/__tests__/__snapshots__/ProgressBar.test.tsx.snap, loveship/components/widgets/__tests__/IndeterminateBar.test.tsx, loveship/components/widgets/__tests__/IndicatorBar.test.tsx, loveship/components/widgets/__tests__/ProgressBar.test.tsx, loveship/components/widgets/__tests__/__snapshots__/IndeterminateBar.test.tsx.snap, loveship/components/widgets/__tests__/__snapshots__/IndicatorBar.test.tsx.snap, loveship/components/widgets/__tests__/__snapshots__/ProgressBar.test.tsx.snap
=> [ProgressBar]: add tests

epam-promo/components/datePickers/DatePicker.tsx, epam-promo/components/datePickers/__tests__/DatePicker.test.tsx, epam-promo/components/datePickers/docs/datePicker.doc.tsx, epam-promo/components/datePickers/docs/rangeDatePicker.doc.tsx, loveship/components/datePickers/DatePicker.tsx, loveship/components/datePickers/__tests__/DatePicker.test.tsx, loveship/components/datePickers/docs/datePicker.doc.tsx, loveship/components/datePickers/docs/rangeDatePicker.doc.tsx, loveship/components/inputs/TimePicker.tsx, uui-components/src/inputs/DatePicker/BaseDatePicker.tsx, uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
=> [DatePicker]: fix twice calling onValueChange on date picker

epam-promo/components/pickers/PickerToggler.scss, loveship/components/pickers/PickerToggler.scss
=> [PickerInput]: fix size of PickerToggler in size-24 loveship skin

uui-components/src/buttons/ButtonBase.tsx
=> [Button]: fix prevent events for elements with clickable child

epam-promo/components/overlays/DropdownMenu.scss, epam-promo/components/overlays/DropdownMenu.tsx, epam-promo/components/overlays/__tests__/__snapshots__/DropdownMenu.test.tsx.snap, uui-components/src/overlays/DropdownContainer.tsx
=> [DropdownMenu]: fix icon position for menuItem

uui/data/processing/views/ArrayListView.ts, uui/data/processing/views/LazyListView.ts
=> [ArrayListView, LazyListView]: fix selectAll behavior

epam-promo/components/inputs/__tests__/__snapshots__/Checkbox.test.tsx.snap, uui-components/src/inputs/Checkbox.scss, uui-components/src/inputs/Checkbox.tsx
=> [Checkbox]: added default value

app/src/data/codesandbox/index.tsx, changelog.md
=> [CodeSandbox]: fixed functionality of modal windows and notifications

loveship/components/buttons/IconButton.scss
=> [IconButton]: fix the IconButton color on focus when the button is disabled

epam-promo/components/inputs/__tests__/__snapshots__/TextInput.test.tsx.snap, epam-promo/components/inputs/__tests__/__snapshots__/TimePicker.test.tsx.snap, epam-promo/components/navigation/MainMenu/Burger/__tests__/__snapshots__/BurgerSearch.test.tsx.snap, loveship/components/inputs/__tests__/__snapshots__/TimePicker.test.tsx.snap, uui-components/src/inputs/TextInput.tsx
=> [SearchInput]: fix to render icons when onAccept and onCancel callback are passed and value is empty

app/src/docs/examples/mainMenu/CustomElements.example.tsx, epam-promo/components/navigation/MainMenu/Burger/Burger.scss, epam-promo/components/navigation/MainMenu/Burger/BurgerButton.scss, epam-promo/components/navigation/MainMenu/Burger/BurgerSearch.scss, loveship/components/navigation/MainMenu/Burger/Burger.scss, loveship/components/navigation/MainMenu/Burger/BurgerButton.scss, loveship/components/navigation/MainMenu/Burger/BurgerSearch.scss
so that all items aligned on one line.
fix #317
=> [BurgerButton]: fix padding for items with and without icon 

epam-promo/components/overlays/DropdownMenu.tsx
=> Don't focus the first action in dropdown menu on menu opening

epam-promo/components/navigation/MainMenu/Burger/BurgerButton.scss
=> [BurgerButton]: fix BurgerButton icon color if isActiveLink=true

app/src/docs/examples/pickerInput/LazyPickerInput.example.tsx, changelog.md, uui/data/processing/LazyDataSource.tsx, uui/data/processing/views/ArrayListView.ts, uui/data/processing/views/BaseListView.tsx, uui/data/processing/views/LazyListView.ts
=> [LazyDataSource]: selectAll attribute

app/src/docs/examples/fileUpload/FileUpload.example.tsx, changelog.md, epam-promo/components/fileUpload/FileCard.scss, epam-promo/components/fileUpload/FileCard.tsx, epam-promo/components/fileUpload/__tests__/__snapshots__/FileCard.test.tsx.snap, epam-promo/i18n.ts
=> [FileCard]: Filecard upload example fix

epam-promo/components/pickers/docs/common.tsx, epam-promo/components/pickers/docs/pickerInput.doc.tsx, epam-promo/components/pickers/docs/pickerModal.doc.tsx, loveship/components/pickers/docs/common.tsx, loveship/components/pickers/docs/pickerInput.doc.tsx, loveship/components/pickers/docs/pickerList.doc.tsx, loveship/components/pickers/docs/pickerModal.doc.tsx, uui-components/src/pickers/PickerBase.tsx, uui-components/src/pickers/PickerInputBase.tsx
=> [PickerInput]: Fix placeholder ending for single selection mode

epam-promo/components/overlays/NotificationCard.tsx, loveship/components/overlays/NotificationCard.tsx, loveship/components/overlays/__tests__/NotificationCard.test.tsx, loveship/components/overlays/__tests__/__snapshots__/NotificationCard.test.tsx.snap
1. Added RawProps attribute to Notification Card top-wrapper and action buttons.
2. Rewrite NotificationCard to FC.
3. Update tests
Closes #361
=> [NotificationCard]: Added rawProps; Rewrite to FC; Adjust tests

loveship/components/inputs/TextArea.scss, loveship/components/inputs/TextInput.scss
=> [TextInput, Textarea][Loveship]: Fix color

app/src/docs/Button.doc.tsx, app/src/docs/assets/loveship/LoveshipColors.doc.tsx, loveship/components/buttons/Button.scss, loveship/components/buttons/docs/button.doc.tsx
=> [Button][Loveship]: Reduce possible colors in property explorer

epam-promo/components/pickers/PickerModal.tsx, loveship/components/pickers/PickerModal.tsx, uui-components/src/pickers/PickerModalBase.tsx
=> [PickerModal]: renderFooter props fixes

changelog.md, epam-promo/components/overlays/Modals.tsx, loveship/components/overlays/Modals.tsx, loveship/components/tables/__tests__/__snapshots__/ColumnPickerFilter.test.tsx.snap, uui/types/components/Modals.ts, yarn.lock
=> [ModalFooter]: add cx prop, fixed date of last release

epam-promo/components/typography/Text.scss, loveship/components/typography/Text.scss
Add typography-inline for Text to have possibility use Anchor inside Text with default color according the skin
=> [TEXT]: add typography-inline

app/src/common/sidebar/Sidebar.tsx, app/src/documents/DocumentsPage.tsx, next-app/components/SideBar.tsx, uui-components/src/layout/Tree.tsx
1. Refactor Tree to FC.
2. Refactor Sidebar to FC
3. Typings clarification
4. Fix datasource update on props change
Closes #337
=> [Tree]: Refactor to FC; Fix datasource update on props change

epam-promo/components/fileUpload/FileCard.tsx, epam-promo/components/tables/DataTableHeaderRow.tsx, loveship/components/tables/DataTableHeaderRow.tsx
to close https://github.com/epam/UUI/issues/334
=> [FileCard]: fix progress behavior, remove extension from name

app/src/docs/other/ReleaseNotes.doc.tsx
=> [Bugfix][Release Notes]: Fix show more redirect and scroll into current release changelog

uui-components/src/pickers/PickerToggler.tsx
=> [PickerToggler][Multi]: Remove redundant toggler focusing on tag clear

epam-promo/components/datePickers/index.ts, loveship/components/datePickers/index.ts
=> Export Calendar & CalendarPresets

epam-promo/components/pickers/PickerModal.tsx, uui-components/src/pickers/PickerBase.tsx, uui-components/src/pickers/PickerInputBase.tsx
fixed issue #504 - search is not working if 'Show only selected' applied
=> [PickerModal]: fixed issue #504 - search is not working

changelog.md, epam-promo/components/pickers/PickerInput.tsx, epam-promo/components/pickers/PickerModal.tsx, loveship/components/pickers/PickerInput.tsx, loveship/components/pickers/PickerModal.tsx, uui-components/src/pickers/PickerBase.tsx, uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerModalBase.tsx, uui-core/types/components/PickerBase.ts, uui/components/pickers/PickerInput.tsx, uui/components/pickers/PickerModal.tsx
=> onClose for renderFooter in PickerInput, IModal for renderFooter in PickerModal

epam-promo/components/widgets/Badge.scss, loveship/components/widgets/Badge.scss
1. removed left margin in base div
2. removed left and right paddings around badge text and corrected margin left according design
=> fixed badge margin and paddings

loveship/components/widgets/PageButton.scss, loveship/components/widgets/Paginator.tsx, loveship/components/widgets/__tests__/__snapshots__/Paginator.test.tsx.snap
fixed loveship skin changed div into nav in Paginator and added 6px margin after 1st button and before laast button.
=> Bugfix/inconsistent paginator #545

epam-promo/components/tables/__tests__/__snapshots__/DataTableRow.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/DataTable.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/DataTableRow.test.tsx.snap, uui-components/src/table/DataTableRow.tsx
fixed area-expended value in the DataTableRow
=> fixed area-expended value in the DataTableRow

epam-promo/components/tables/__tests__/__snapshots__/DataTableRow.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/DataTableRow.test.tsx.snap, uui-components/src/table/DataTableRow.tsx
fixed aria-expanded value wheh undefined
=> Bugfix/incorrect aria expanded row prop #546

changelog.md, epam-promo/components/fileUpload/DropSpot.scss, epam-promo/components/fileUpload/DropSpot.tsx, uui-components/src/widgets/DropSpot.tsx
changed the visualization of the drop area, when the drag starts, the border of the drop area turns blue, and when the file is over the drop area, the background of the drop area also turns blue.
=> Bugfix/DropSpot drag&drop #562

epam-promo/components/pickers/PickerToggler.tsx, loveship/components/pickers/PickerToggler.tsx, uui-components/src/pickers/PickerToggler.tsx
=> Inputs extra padding and tags on disabled state #578

epam-promo/components/inputs/docs/multiSwitch.doc.tsx, loveship/components/inputs/MultiSwitch.tsx, loveship/components/inputs/docs/multiSwitch.doc.tsx
=> Add 'isDisabled' prop to MultiSwitch in Loveship (like in Promo) #588

app/src/demo/tables/filteredTable/FilteredTable.tsx, app/src/demo/tables/filteredTable/filters.tsx, epam-promo/components/filters/FilterDataPickerBody.tsx, epam-promo/components/filters/FilterItemBody.tsx, epam-promo/components/filters/FilterRangeDatePickerBody.tsx, epam-promo/components/filters/FiltersToolbar.tsx, epam-promo/components/filters/FiltersToolbarItem.tsx, epam-promo/i18n.ts, uui-core/types/tables.ts
filters configuration: Add **getName**, **format** and **valueType** properties;
Change all texts to i18n messages;
Fix RangeDatePicker: add **changeIsOpen** property;
=> [FilterToolbar]: fixe bugs, refactoring, extend filter configuration

epam-promo/components/datePickers/RangeDatePicker.tsx, epam-promo/components/datePickers/__tests__/DatePicker.test.tsx, epam-promo/components/datePickers/__tests__/RangeDataPicker.test.tsx, epam-promo/components/filters/FilterRangeDatePickerBody.tsx, loveship/components/datePickers/RangeDatePicker.tsx, loveship/components/datePickers/__tests__/RangeDataPicker.test.tsx, uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx, uui-core/types/components/datePicker/BaseRangeDatePicker.ts
https://github.com/epam/UUI/issues/761
=> [RangeDatePicker]: added onFocus and onBlur props #761

app/src/sandbox/skills/SkillsBatteryPopover.scss, app/src/sandbox/skills/SkillsBatteryPopover.tsx
https://github.com/epam/UUI/issues/757
=> [Tooltip]: fixed paddings #757

app/src/docs/examples/mainMenu/Basic.example.tsx, app/src/docs/examples/mainMenu/Responsive.example.tsx
https://github.com/epam/UUI/issues/780
=> [MainMenu]: fixed images path for static files #780

epam-promo/components/layout/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap, epam-promo/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, epam-promo/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, loveship/components/inputs/__tests__/__snapshots__/Checkbox.test.tsx.snap, loveship/components/layout/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, loveship/components/tables/__tests__/__snapshots__/DataTableHeaderRow.test.tsx.snap, uui-components/src/inputs/Checkbox.tsx
https://github.com/epam/UUI/issues/766
After review removed previous changes with hack for `indeterminate` attribute. And added mixed value as aria-checked attributes. According to A11y docs - https://w3c.github.io/aria-practices/examples/checkbox/checkbox-mixed.html.
=> [Checkbox]: added indeterminate attribute #766

app/src/common/appFooterDemo/demoToolbar/useDemoDescriptionEditor.tsx, changelog.md, uui-core/services/ModalContext.ts, uui-core/types/props.ts
https://github.com/epam/UUI/issues/737
=> [ModalContext]: added argument to abort method props #737

app/src/docs/other/Team.doc.tsx
=> [Site]: change team members list

epam-promo/components/datePickers/__tests__/RangeDataPicker.test.tsx, loveship/components/datePickers/__tests__/RangeDataPicker.test.tsx, uui-components/src/inputs/DatePicker/BaseDatePicker.tsx, uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx, uui-components/src/inputs/DatePicker/DatePickerBodyBase.tsx, uui-components/src/inputs/DatePicker/helpers.ts
Info ℹ️ 
https://github.com/epam/UUI/issues/806
https://github.com/epam/UUI/issues/828
=> [DatePicker][RangeDatePicker]: added ability to enter date in format different than props.format #806 and #828

uui-components/src/inputs/NumericInput.tsx
- prevent change value onScroll
=> [NumericInput] change value onscroll

uui-components/src/inputs/NumericInput.tsx
- add validation & avoid to set min to unset value
=> [NumericInput]: add validation

app/package.json, app/src/data/codesandbox/package.json, app/src/docs/examples/tables/LazyTable.example.tsx, extra/ideas/iqueryable.tsx, extra/index.tsx, loveship/components/dnd/DropSpot.tsx, loveship/components/pickers/PickerList.tsx, next-app/package.json, next-app/yarn.lock, package.json, tsconfig.json, uui-build/package.json, uui-components/src/overlays/Tooltip.tsx, uui-components/src/table/columnsConfigurationModal/index.ts, uui-components/src/widgets/AvatarStack.tsx, uui-core/data/validation/index.ts, yarn.lock
=> Migrate to newever version of Typescript "4.5.4" -> "4.9.3".

.stylelintrc.js, app/.config/constants.js, app/.config/craco.config.js, app/.config/utils/configUtils.js, app/.config/utils/packageUtils.js, app/package.json, app/src/demo/demoItemCard/DemoItemCard.scss, app/src/documents/DocumentsPage.tsx, app/src/landing/BenefitsBlock.scss, app/src/landing/ContactsBlock.scss, app/src/landing/ReleasesBlock.scss, app/src/landing/TeamBlock.scss, app/src/sandbox/draft-rte/DraftRTEDemo.tsx, app/src/sandbox/project/RowKebabButton.tsx, app/src/sandbox/project/demoData.ts, app/src/sandbox/project/types.ts, app/src/sandbox/tablePaged/DemoTablePaged.tsx, app/src/sandbox/tablePaged/types.ts, app/src/setupProxy.js, app/tsconfig.json, package.json, server/api/docs.js, server/app.js, server/utils/envUtils.js, uui-core/src/helpers/cx.ts, yarn.lock
=> Migrate "app" module to latest CRA.

tsconfig.json, uui-build/config/webpack.config.js, yarn.lock
=> Fix issue with build module task

app/src/common/docs/ComponentEditor.scss, app/src/common/sidebar/Sidebar.scss, app/src/docs/assets/IconsPage.scss, public/docs/componentsPropsSet.json, uui-build/getComponentsPropsSet.ts
1) Sort file names & props 2) Fix three value "flex" property
=> 1) Sort file names & props 2) Fix three value "flex" property

epam-promo/components/datePickers/__tests__/RangeDataPicker.test.tsx, loveship/components/datePickers/__tests__/RangeDataPicker.test.tsx, uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
Info ℹ️ 
https://github.com/epam/UUI/issues/736
=> [RangeDatePicker]: handle focus also from to value #736

changelog.md, epam-promo/components/buttons/TabButton.scss, loveship/components/buttons/TabButton.scss
Info ℹ️ 
https://github.com/epam/UUI/issues/889
=> [Vertical Tab Button]: text is trimmed in case of long caption #889

changelog.md, epam-promo/components/inputs/__tests__/__snapshots__/Switch.test.tsx.snap, loveship/components/inputs/__tests__/__snapshots__/Switch.test.tsx.snap, uui-components/src/inputs/Switch.tsx
- remove margin-left if there is no label
=> [Switch]: remove margin-left if there is no label

loveship/components/layout/docs/controlGroup.doc.tsx
- controlGroup explorer, update button color for loveship
=> [Docs]: controlGroup explorer, update button color for loveship

app/build-config/craco.config.js, uui-build/scripts/packageModulesForLocalTest.js, uui-build/utils/cmdUtils.js, uui-components/src/layout/ScrollBars.tsx, uui-core/src/types/props.ts
1) Fix issue when TS typechecking is missed in watch mode.
2) Fix imports from 'react-custom-scrollbars-2'
3) Fix TS compile error in "uui-core/src/types/props.ts"
=> Fix some issues with build

app/src/docs/other/Team.doc.tsx
Added a new team member to the list of teammates/contributors.
=> [Site]: Add new team member to the list.

epam-promo/components/filters/FilterRangeDatePickerBody.tsx, uui-components/src/inputs/DatePicker/BaseDatePicker.tsx, uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx, uui-components/src/inputs/DatePicker/DatePickerBodyBase.tsx, uui-components/src/inputs/DatePicker/helpers.ts
Info ℹ️ 
- Fixed issue if `props.format` = `DD/MM/YYYY` which is conflicting with supported format `MM/DD/YYYY`
- Fixed Filter panel issue
=> [DatePicker][RangeDatePicker]: fixed filter panel issue and format issue with conflicting format

uui-components/src/inputs/NumericInput.tsx, uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree.test.ts
Closes **BUG 1** and **BUG 2** at: https://github.com/epam/UUI/issues/882
Closes: https://github.com/epam/UUI/issues/879
=> [PickerInput]: prevented check if `onValueChange` is not changing values

templates/uui-nextjs-template/template/package.json, templates/uui-nextjs-template/template/yarn.lock
Closes: https://github.com/epam/UUI/issues/814
The current problem with `window` in the latest `@epam/uui-core` is fixed at https://github.com/epam/UUI/pull/937.
Updated `yarn.lock` to prevent installing `@epam/assets`, `@epam/uui-components`, and `@epam/uui-core` of `v4.4.0`.
=> [NextJS]: fixed import epam uui and updated yarn.lock

epam-promo/components/tables/columnsConfigurationModal/ColumnsConfigurationModal.tsx, loveship/components/tables/columnsConfigurationModal/ColumnsConfigurationModal.tsx
Closes: https://github.com/epam/UUI/issues/878, the last comment.
=> [ColumnsConfigurationModal]: changed tooltip color

app/src/common/docs/ComponentEditor.tsx
Check for undefined at the component editor getProps
=> [Checkbox Group] checkbox group selecting error

app/src/docs/_props/epam-promo/components/datePickers/datePicker.props.tsx, app/src/docs/_props/epam-promo/components/datePickers/rangeDatePicker.props.tsx, app/src/docs/_props/loveship/components/datePickers/datePicker.props.tsx, app/src/docs/_props/loveship/components/datePickers/rangeDatePicker.props.tsx, uui/components/datePickers/DatePicker.scss
Info ℹ️ 
https://github.com/epam/UUI/issues/904
- Fix footers for date pickers.
- Added opportunity to enter custom format manually.
=> [DatePicker][RangeDatePicker]: fix footers and allow to enter formats #904

app/src/common/docs/DocExample.scss, app/src/docs/_examples/pickerInput/CustomUserRow.example.tsx, app/src/docs/_examples/pickerInput/LazyPickerInput.example.tsx, app/src/docs/_examples/pickerInput/LazyTreeInput.example.tsx, app/src/docs/_examples/pickerInput/SearchPositions.example.tsx
Info ℹ️ 
https://github.com/epam/UUI/issues/953
Removed additional container from examples as we already have one and fix search input examples.
=> [PickerInput]: selected values are outside of container #953

app/src/demo/form/DemoForm.tsx, epam-promo/components/forms/Form.tsx, epam-promo/components/forms/useForm.tsx, loveship/components/forms/Form.tsx, next-app/pages/demoForm.tsx
Info ℹ️ 
https://github.com/epam/UUI/issues/981
=> [Notification]: error in console appears after notification disappears #981

uui-components/src/pickers/PickerListBase.tsx
Fixed: https://github.com/epam/UUI/issues/811
=> [PickerList]: fixed list sorting order

uui-core/src/data/processing/views/ArrayListView.ts, uui-core/src/data/processing/views/Tree.ts, uui-core/src/data/processing/views/__tests__/Tree.test.ts
Moved the filtering/searching/sorting logic from `ArrayListView` to `Tree`.
=> [ArrayListView] Moved filtering/sorting/search from ArrayListView to Tree.

uui-components/src/pickers/PickerListBase.tsx
Fixed sorting behavior if no sorting was passed.
=> [PickerList]: fixed sorting behavior.

app/src/common/docs/ComponentEditor.tsx, uui-docs/src/DocBuilder.ts
Info ℹ️ 
- Fixed editing input values
- Fixed code block
=> [ComponentEditor]: fixed input values and code block in property explorer

app/src/docs/_examples/tooltip/Types.example.tsx, app/src/docs/_examples/tooltip/TypesExample.scss, app/src/docs/_examples/tooltip/Variants.example.tsx, public/docs/content/examples-tooltip-Placement.json, public/docs/content/examples-tooltip-Types.json
=> [Docs]: tooltip example refactor

uui-core/src/data/processing/views/ArrayListView.ts, uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts
Completes part of: https://github.com/epam/UUI/issues/1036
Added functionality of cascade updating (filtering/searching/sorting) of the tree only if it is required.
=> [ArrayListView]: added conditional filtering/searching/sorting the tree

epam-promo/components/filters/FilterRangeDatePickerBody.tsx, epam-promo/components/filters/FiltersPanelItem.tsx
Info: ℹ️ 
https://github.com/epam/UUI/issues/1047
- Added fix for changeIsOpen for RangeDatePicker
- Fix for changing predicate for numeric
=> [FilterRangeDatePicker][FilterPanelItem]: issues with selecting values in filter "Salary" and "Birth date" #1047

uui/components/filters/FilterRangeDatePickerBody.tsx, uui/components/filters/FiltersPanelItem.tsx
Info ℹ️ 
https://github.com/epam/UUI/pull/1059
- Added fix for changeIsOpen for RangeDatePicker
- Fix for changing predicate for numeric
=> [FilterPanelItem][FilterRangeDatePicker]: Issues with selecting values in filter "Salary" and "Birth date" #1047

.github/workflows/base.yml, .github/workflows/dev.yml, .github/workflows/prod.yml, .github/workflows/qa.yml
Update workflow for PROD environment
=> EPMPPA-1896 Update workflow for production environment

.github/workflows/base.yml, .github/workflows/dev.yml, .github/workflows/prod.yml, .github/workflows/qa.yml
Update common chart version, update workflow for PROD environment
=> EPMPPA-1896 Update workflow for production environment (#1066)

epam-assets/scss/typography.scss, epam-promo/assets/styles/typography-mixins.scss, loveship/assets/styles/scss/typography-mixins.scss
Closes #1070
Now links for Typography underlined for UUI4.
=> [Typography] Underline links in typography 

epam-promo/components/buttons/__tests__/__snapshots__/Button.test.tsx.snap, epam-promo/components/buttons/__tests__/__snapshots__/IconButton.test.tsx.snap, epam-promo/components/buttons/__tests__/__snapshots__/LinkButton.test.tsx.snap, epam-promo/components/buttons/__tests__/__snapshots__/TabButton.test.tsx.snap, epam-promo/components/buttons/__tests__/__snapshots__/VerticalTabButton.test.tsx.snap, epam-promo/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, epam-promo/components/widgets/__tests__/__snapshots__/Paginator.test.tsx.snap, loveship/components/buttons/__tests__/__snapshots__/Button.test.tsx.snap, loveship/components/buttons/__tests__/__snapshots__/IconButton.test.tsx.snap, loveship/components/buttons/__tests__/__snapshots__/LinkButton.test.tsx.snap, loveship/components/buttons/__tests__/__snapshots__/TabButton.test.tsx.snap, loveship/components/buttons/__tests__/__snapshots__/VerticalTabButton.test.tsx.snap, loveship/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, loveship/components/widgets/__tests__/__snapshots__/Paginator.test.tsx.snap, uui-components/src/buttons/ButtonBase.tsx
Fixes #1057
This PR applied disabled attribute when button disabled.
=> [ButtonBase] Apply missing `disabled` attribute when needed

uui-core/src/data/processing/views/LazyListView.ts
Added logging of errors on exception in `loadMissingImpl` function.
=> [LazyListView]: logging of error on exception in `loadMissingImpl`.

uui-editor/src/implementation/NoteBar.tsx
This PR fixes note button bar display
=> [SlateEditor] Fix note button bar display

uui-editor/src/implementation/Toolbar.tsx, uui-editor/src/plate/plugins/tablePlugin/Table.scss, uui-editor/src/plate/plugins/tablePlugin/TableCell.tsx, uui-editor/src/plate/plugins/tablePlugin/TableHeaderCell.tsx, uui-editor/src/plate/plugins/tablePlugin/TableRow.tsx, uui-editor/src/plate/plugins/tablePlugin/tablePlugin.tsx
Fixes:
- fixes toolbar iteraction
- cell content alignment set to left
- now resize works with header borders
- now resizing works correctly even when removing columns
- small border styles fixed
=> [SlateEditor] Fix table alignment

uui-editor/src/SlateEditor.tsx
Removes border in readonly mode
=> [SlateEditor] Remove border in readonly mode

uui-editor/src/plate/plugins/tablePlugin/Table.scss, uui-editor/src/plate/plugins/tablePlugin/tablePlugin.tsx
FIxes column addition in FF in Safari
=> [SlateEditor] Fixes column addition in FF

uui-editor/src/plate/plugins/tablePlugin/deleteColumn.ts, uui-editor/src/plate/plugins/tablePlugin/tablePlugin.tsx
Fixes second column remove action by simplifying column deletion implementation from plate.
**Before:** 
https://user-images.githubusercontent.com/39378793/226890565-f9de77dd-e4f5-48fb-a055-fa4ce0c4eab2.mp4
=> [SlateEditor] Fix second column remove

uui-editor/src/implementation/Toolbar.tsx, uui-editor/src/plate/plugins/tablePlugin/Table.scss
Tollbar jumps to the edge of the screen on clicking empty cell.
=> [SlateEditor] Fix table toolbar appearing in FF

app/src/docs/_examples/tables/EditableTable.example.tsx, app/src/docs/_examples/tables/TablesExamples.scss, uui-core/src/data/processing/views/ArrayListView.ts
Closes part of: https://github.com/epam/UUI/issues/1036
Updated Editable Table demo according to the design suggestions.
=> [DataTable] Editable table demo update

uui-core/src/data/forms/useForm.ts, uui/components/forms/useForm.tsx
Info ℹ️ 
https://github.com/epam/UUI/issues/1137
=> [DemoForm]: Entered data can't be delete after reload page #1137

uui-components/src/table/DataTableCell.scss
fixed a bug with table resize
Related to:
https://github.com/epam/UUI/issues/1163
=> [1163] - fixed a bug with table resize

app/src/common/docs/ComponentEditor.tsx, app/src/common/sidebar/Sidebar.tsx, app/src/common/sidebar/SidebarButton.scss, app/src/common/sidebar/SidebarButton.tsx, app/src/docs/_props/epam-promo/components/navigation/anchor.props.tsx, app/src/docs/_props/epam-promo/components/navigation/anchor.scss, app/src/docs/_props/loveship/components/navigation/anchor.props.tsx, app/src/docs/_props/loveship/components/navigation/anchor.scss
…nstead Button in SidebarButton, remade example for Anchor's property explorer
=> corrected IconButton colors in ComponentEditor, new Anchor example

uui-editor/src/plate/plugins/notePlugin/notePlugin.tsx, uui-editor/src/plate/plugins/toDoListPlugin/toDoListPlugin.tsx, uui-editor/src/plate/plugins/uploadFilePlugin/file_uploader.ts
Prevents default when needed (for note elements only).
=> [SlateEditor] Fix insert data behavior

uui-core/src/data/processing/views/ArrayListView.ts
- Fixed infinity loading while results were not found for `AsyncListView`/`ArrayListView`.
- Fixed empty checked elements if checked elements and started searching for others.
=> [Datasources Rework]: fixed ArrayListView

uui-components/src/pickers/PickerBase.tsx, uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree.test.ts, uui-core/src/data/processing/views/tree/BaseTree.ts, uui-core/src/data/processing/views/tree/ITree.ts, uui-core/src/types/dataSources.ts, uui/components/pickers/PickerInput.tsx
Closes: https://github.com/epam/UUI/issues/683
https://user-images.githubusercontent.com/22456368/230885239-d58d141b-794e-4583-a04e-6001a883e3fa.mov
=> [PickerInput]: fixes selected items order

uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/LazyListView.ts, uui-core/src/data/processing/views/tree/EditableTree.ts
Closes: https://github.com/epam/UUI/issues/1123
=> [LazyListView] Correctly displayed partially checked nodes.

app/src/docs/_examples/pickerInput/TogglerConfiguration.example.tsx, uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerToggler.tsx, uui-core/src/types/props.ts
Closes: https://github.com/epam/UUI/issues/1165
=> [PickerInput]: fixed behavior of PickerInput for alternative Inputs.

uui-editor/src/migration.ts, uui-editor/src/plate/plugins/imagePlugin/ImageBlock.tsx, uui-editor/src/plate/plugins/imagePlugin/Toolbar.tsx
This PR
- improves pasting icons
- add ability to pasting images from internet
=> [SlateEditor] Improve image render

uui-editor/src/plate/plugins/imagePlugin/ImageBlock.tsx, uui-editor/src/plate/plugins/imagePlugin/ImageElement.tsx
Fixes pasting content from word which has images.
=> [SlateEditor] fix pasting images inside a text from word

app/src/demo/tables/masterDetailedTable/FilterPanel/ColumnsBlock/ColumnsBlock.tsx, uui-components/src/pickers/KeyboardUtils.tsx, uui-components/src/pickers/PickerBase.tsx, uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerListBase.tsx, uui-components/src/pickers/PickerModalBase.tsx, uui-components/src/pickers/PickerToggler.tsx, uui-core/src/data/processing/ArrayDataSource.tsx, uui-core/src/data/processing/AsyncDataSource.tsx, uui-core/src/data/processing/hooks/useList.ts, uui-core/src/data/processing/hooks/useView.ts, uui-core/src/data/processing/views/ArrayListView.ts, uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/LazyListView.ts, uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.complex-ids.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree.test.ts, uui-core/src/data/processing/views/tree/EditableTree.ts, uui-core/src/types/dataSources.ts, uui-core/src/types/props.ts, uui/components/filters/FilterPickerBody.tsx, uui/components/pickers/DataPickerFooter.tsx, uui/components/pickers/PickerList.tsx, uui/components/pickers/PickerModal.tsx, uui/components/pickers/PickerToggler.tsx, uui/components/pickers/__tests__/PickerInput.test.tsx, uui/components/pickers/__tests__/PickerToggler.test.tsx, uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerToggler.test.tsx.snap
Fixed some performance issues and logic issues.
=> [Datasources]: fixed performance and logic issues.

changelog.md, uui-components/src/inputs/TimePickerBody.tsx
added max values to hours and minutes in datepicker
Related to:
https://github.com/epam/UUI/issues/1207
=> Bugfix/add maxvalues datepicker #1207

uui-editor/src/plate/plugins/imagePlugin/ImageBlock.tsx
Fixes image duplication on resizing, refactoring
=> [SlateEditor] Fix image duplication on resize

uui-components/src/pickers/PickerInputBase.tsx, uui-components/src/pickers/PickerToggler.tsx, uui-components/src/pickers/helpers.ts, uui/components/pickers/PickerToggler.tsx, uui/components/pickers/helpers.ts
Fixed problem with reduced toggler items, rendered at PickerToggler.
=> [PickerInput]: fixed reduced toggler max items.

uui-core/src/data/processing/views/ArrayListView.ts
Fixed failing datasource on theme change in property explorer for PickerInput.
=> [ArrayListView]: fixed failing datasource on theme change.

uui-components/src/inputs/TimePickerBody.tsx
https://github.com/epam/UUI/issues/1207
fixed an issue when props.format is undefined
=> [1207] - fixed timepicker max hours

uui-editor/src/plate/plugins/imagePlugin/ImageBlock.scss, uui-editor/src/plate/plugins/imagePlugin/ImageBlock.tsx
Fix caption display for loaded images, aligns caption center, removes overflow.
=> [SlateEditor] Fix caption display for loaded images

app/src/docs/_examples/richTextEditor/WithInnerScroll.example.tsx
Fixes inner scroll example when it's empty
=> [SlateEditor] Fix empty inner scroll

uui-editor/src/plate/plugins/tablePlugin/tablePlugin.tsx
=> [SlateEditor] Hide table toolbar 

uui-editor/src/plate/plugins/iframePlugin/iframePlugin.tsx
Allows pasting iframe from clipboard.
=> [SlateEditor] Allow pasting iframe from clipboard

epam-assets/theme/theme_vanilla_thunder.scss, uui/components/buttons/Button/Button.scss, uui/components/buttons/LinkButton.scss, uui/components/buttons/TabButton.scss, uui/components/datePickers/Calendar.scss, uui/components/datePickers/DatePicker.scss, uui/components/filters/FilterPanelItemToggler.scss, uui/components/filters/FiltersPanelItem.scss, uui/components/inputs/Checkbox.scss, uui/components/inputs/RadioInput.scss, uui/components/inputs/Switch.scss, uui/components/inputs/TextArea.scss, uui/components/inputs/TextInput.scss, uui/components/layout/Accordion.scss, uui/components/layout/LabeledInput.scss, uui/components/navigation/MainMenu/Burger/BurgerButton.scss, uui/components/navigation/MainMenu/Burger/BurgerGroupHeader.scss, uui/components/navigation/MainMenu/Burger/BurgerSearch.scss, uui/components/navigation/MainMenu/MainMenu.scss, uui/components/navigation/MainMenu/MainMenuButton.scss, uui/components/navigation/MainMenu/MainMenuSearch.scss, uui/components/overlays/DropdownMenu.scss, uui/components/overlays/Tooltip.scss, uui/components/pickers/PickerToggler.scss, uui/components/tables/DataTableHeaderCell.scss, uui/components/widgets/AvatarStack.scss, uui/components/widgets/Badge.scss, uui/components/widgets/Paginator.scss, uui/components/widgets/Tag.scss
Add 'font-weight' & 'font-weight' tokens support
=> [Theming]: add font-weight support

uui-build/linting/eslintrc.base.js, uui-build/linting/utils/eslintRulesFromAirbnb.js
=> adjust eslint rules - feedback

uui-editor/src/SlateEditor.tsx
=> [SlateEditor] Fix text highlight

epam-assets/scss/promo/typography.scss
=> [Typography] Underline missed links for typography

uui-editor/src/plate/plugins/linkPlugin/link.scss, uui-editor/src/plate/plugins/linkPlugin/linkPlugin.tsx
Fixes links highlighting using `shift`.
=> [SlateEditor] Fix links highlighling using `shift`

app/src/common/docs/DocExample.tsx
https://github.com/epam/UUI/issues/1259
[1259] - positioning fix for documentation
=> [1259] - positioning fix for documentation

test-utils/package.json
=> adjustments

public/docs/content/unitTestingGuide-3-tools.json, test-utils/readme.md
=> add readme for uui-test-utils

app/src/demo/tables/filteredTable/filters.tsx, app/src/docs/_examples/tables/FiltersPanelBasic.example.tsx, changelog.md, uui-core/src/types/tables.ts, uui/components/filters/FilterRangeDatePickerBody.tsx
https://github.com/epam/UUI/issues/1191
[1191] - added possibility to provide presets to table filters
=> [1191] - added possibility to provide presets to table filters

app/src/docs/_examples/pickerInput/GetRowOptions.example.tsx
Updated the example of `getRowOptions` in `PickerInput`.
=> [PickerInput]: getRowOptions example updated.

.github/workflows/base.yml
=> EPMPPA Increase minor version, +semver: minor

README.md, changelog.md, package.json, public/docs/content/unitTestingGuide-3-tools.json, templates/uui-cra-template/template.json, templates/uui-cra-template/template/src/pages/MainPage.test.tsx, test-utils/readme.md
=> Update changelog with changes related to unit tests

app/src/docs/_examples/tooltip/CustomMarkup.example.tsx, changelog.md, uui/components/overlays/Tooltip.scss
=> fixed Tooltip max-with in styles

app/src/docs/_props/loveship/components/buttons/tabButton.props.ts, loveship/components/buttons/__tests__/__snapshots__/TabButton.test.tsx.snap, loveship/components/buttons/__tests__/__snapshots__/VerticalTabButton.test.tsx.snap, uui/components/buttons/TabButton.tsx, uui/components/buttons/__tests__/__snapshots__/TabButton.test.tsx.snap, uui/components/buttons/__tests__/__snapshots__/VerticalTabButton.test.tsx.snap, uui/components/datePickers/RangeDatePicker.scss, uui/components/filters/PresetPanel/__tests__/__snapshots__/Preset.test.tsx.snap
=> Bugfix/TabButton informer  and RangeDatePicker

app/app.d.ts, app/build-config/craco.config.js, draft-rte/globals.d.ts, epam-promo/components/buttons/Button.tsx, epam-promo/globals.d.ts, extra/globals.d.ts, loveship/components/buttons/Button.tsx, loveship/globals.d.ts, test-utils/globals.d.ts, uui-build/rollup/rollup.config.js, uui-components/globals.d.ts, uui-core/globals.d.ts, uui-core/src/helpers/index.ts, uui-core/src/helpers/uuiLogger.ts, uui-db/globals.d.ts, uui-docs/globals.d.ts, uui-editor/globals.d.ts, uui-timeline/globals.d.ts, uui/globals.d.ts
=> add dev logger

app/src/docs/_examples/virtualList/Advanced.example.tsx, uui/components/inputs/TextInput.scss, uui/components/pickers/PickerModal.scss
=> Bugfix/VirtualList & TtextInput  & PickerModal fixes

app/package.json, extra/package.json, public/docs/content/unitTestingGuide-3-tools.json, uui-db/package.json, yarn.lock
=> remove unused dependencies related to unit tests

uui-editor/src/plate/plugins/linkPlugin/AddLinkModal.tsx, uui-editor/src/plate/plugins/linkPlugin/linkPlugin.tsx
=> [SlateEditor] fix pasting links as text

server/app.js, uui/components/filters/PresetPanel/PresetInput.tsx, uui/components/filters/PresetPanel/PresetsPanel.module.scss, uui/components/filters/PresetPanel/PresetsPanel.tsx, uui/components/filters/PresetPanel/__tests__/__snapshots__/PresetInput.test.tsx.snap, uui/components/filters/PresetPanel/__tests__/__snapshots__/presetsPanel.test.tsx.snap
https://github.com/epam/UUI/issues/992
- Added limitation for preset input(max length 50)
- Fix `413` error for cities payload on filter table demo
- Fix scroll inside dropdown container
Case1 and Case 3 is not reproducible for develop. 
Things to check before merging:
=> [PresetsPanel]: set of minor issues #992

epam-assets/package.json, uui-build/scripts/compileScss.js
=> Build theme folder in assets

app/src/sandbox/productsTable/ProductsTableDemo.tsx, uui-core/src/data/processing/hooks/useList.ts
Fixes revert functionality of the `useForm`, using `useListView`.
=> [useListView]: fixes revert form functionality.

app/src/common/appFooterDemo/demoToolbar/useDemoDescriptionEditor.tsx, uui/components/forms/Form.tsx
https://github.com/epam/UUI/issues/1137
Removed unneeded catch handler from the form.
=> [Sandbox->Form]: Entered data can't be delete after reload page #1137

uui-editor/src/plate/plugins/tablePlugin/Table.tsx, uui-editor/src/plate/plugins/tablePlugin/TableCellRenderer.tsx
cells selection bug investigation
=> [SlateEditor] Table cell selection investigation

uui-build/package.json
=> return back the script which was accidentally deleted

uui-build/package.json, uui-build/utils/compileScssUtils.js
=> remove unused functionality from the script

app/src/sandbox/productsTable/columns.tsx
Fixed unknown colors in the Products table demo example.
=> [ProductsTableDemo]: fixed `Unknown` colors.

uui-editor/src/SlateEditor.tsx, uui-editor/src/plate/plugins/deserializeDocxPlugin/cleanDocx.ts, uui-editor/src/plate/plugins/deserializeDocxPlugin/cleanHtmlEmptyElements.ts, uui-editor/src/plate/plugins/deserializeDocxPlugin/deserializeDocxPlugin.ts, uui-editor/src/plate/plugins/tablePlugin/Resizable.tsx, uui-editor/src/plate/plugins/tablePlugin/TableCellRenderer.tsx, uui-editor/todo.md
Fixes resize border jumps when cells merged.
=> [SlateEditor] Fix resize border jumps

uui-editor/src/SlateEditor.tsx
Fix error with editor value updates
=> [SlateEditor] Fix error with editor value update

app/src/docs/_props/epam-promo/components/layout/iconContainer.props.tsx, app/src/docs/_props/loveship/components/layout/iconContainer.props.tsx, epam-promo/components/fileUpload/__tests__/__snapshots__/DropSpot.test.tsx.snap, epam-promo/components/fileUpload/__tests__/__snapshots__/FileCard.test.tsx.snap, epam-promo/components/index.ts, epam-promo/components/layout/IconContainer.module.scss, epam-promo/components/layout/IconContainer.tsx, epam-promo/components/layout/index.tsx, epam-promo/components/overlays/Tooltip.tsx, loveship/components/index.ts, loveship/components/layout/IconContainer.module.scss, loveship/components/layout/IconContainer.tsx, loveship/components/layout/index.ts, uui/components/overlays/Tooltip.tsx
…r: returned property color in both skins and added warning about it's deprecation
=> Tooltip: fixed, IconContainer restored prop color with warn

.lintstagedrc.js
=> Add possibility to ignore certain dirs during lint-staged

changelog.md, epam-promo/components/errors/ErrorHandler.tsx, loveship/components/app/ErrorHandler.tsx
https://github.com/epam/UUI/issues/1330
Added custom callback which will handle notification type of error. Can be used as mentioned in the issue example.
=> [ErrorHandler]: added props for notification error

uui-editor/src/plate/plugins/toDoListPlugin/ToDoItem.module.scss, uui-editor/src/plate/plugins/toDoListPlugin/ToDoItem.tsx, uui-editor/todo.md
=> [SlateEditor] Fix checkbox in ff

uui-editor/src/plate/plugins/linkPlugin/isUrl.ts, uui-editor/src/plate/plugins/linkPlugin/linkPlugin.tsx, uui-editor/todo.md
=> [SlateEditor] Fix email links

uui-editor/src/plate/plugins/attachmentPlugin/attachmentPlugin.tsx, uui-editor/src/plate/plugins/iframePlugin/iframePlugin.tsx, uui-editor/src/plate/plugins/imagePlugin/imagePlugin.tsx, uui-editor/src/plate/plugins/separatorPlugin/separatorPlugin.tsx
fixes remove actions on attach and separator elements
=> [SlateEditor] Fix attachments / separator remove events

uui-editor/src/implementation/NoteBar.tsx
=> [SlateEditor] Fix note plugin toolbar

uui-editor/src/implementation/HeaderBar.tsx, uui-editor/src/plate/plugins/placeholderPlugin/placeholderPlugin.tsx
=> [SlateEditor] Fix header error

uui-core/src/data/processing/views/tree/EditableTree.ts
Fixed AsyncDataSource selectAll functionality.
=> [AsyncDataSource]: fixed select all

uui-components/src/inputs/Checkbox.tsx, uui-editor/src/plate/plugins/toDoListPlugin/ToDoItem.module.scss, uui-editor/src/plate/plugins/toDoListPlugin/ToDoItem.tsx, uui-editor/src/plate/plugins/toDoListPlugin/toDoListPlugin.tsx
- now more stable on ff
- there is no cursor jumps on toggle
- checking in table cell works
=> [SlateEditor] Improve checkbox

app/src/data/codesandbox/tsconfig.json, app/src/docs/_examples/pickerModal/BasicPickerModal.example.tsx
=> fixed svc import in PickerModal, edit sandbox tsconfig

changelog.md, uui/components/filters/FiltersPanelItem.module.scss, uui/components/filters/FiltersPanelItem.tsx
https://github.com/epam/UUI/issues/1374 
Added title:
=> [FiltersPanel]: move picker title to the header in mobile view #1374

app/src/demo/tables/filteredTable/FilteredTable.tsx, app/src/demo/tables/filteredTable/filters.tsx, app/src/docs/_examples/tables/FiltersPanelBasic.example.tsx, changelog.md, epam-assets/theme/theme_promo.scss, epam-assets/theme/theme_vanilla_thunder.scss, epam-promo/components/buttons/Button.module.scss, epam-promo/components/buttons/Button.tsx, uui-build/linting/stylelintrc.base.js, uui-core/src/types/components/filterItemBody.ts, uui-core/src/types/tables.ts, uui/components/buttons/Button/Button.module.scss, uui/components/filters/FilterDatePickerBody.tsx, uui/components/filters/FilterItemBody.tsx, uui/components/filters/FilterNumericBody.tsx, uui/components/filters/FilterPanelItemToggler.module.scss, uui/components/filters/FilterPanelItemToggler.tsx, uui/components/filters/FilterPickerBody.tsx, uui/components/filters/FilterRangeDatePickerBody.tsx, uui/components/filters/FiltersPanel.tsx, uui/components/filters/FiltersPanelItem.module.scss, uui/components/filters/FiltersPanelItem.tsx, uui/components/filters/PresetPanel/PresetsPanel.tsx, uui/components/pickers/DataPickerBody.module.scss, uui/components/pickers/DataPickerHeader.tsx, uui/i18n.ts
- Added possibility to hide search for exact filter using `showSearch` prop in config.
- Added sizes for panel.
- Fixed styles for body & toggler according to design.
=> Feature: filter improvements

uui-build/linting/eslintrc.base.js, uui-build/linting/utils/rulesToBeFixed.js
=> remove unused disables only for the full set of rules.

test-utils/package.json, test-utils/src/rendering/setupComponentUtils.tsx
=> Remove dependency on jest because it can be used in Vitest as well.

uui-core/src/hooks/useTableState/useTableState.ts
Fixed checking elements and selecting elements + details overview.
=> [Demo Table]: fixed checking of elements and selecting + details overview.

.github/workflows/trackBundleSize.yml
=> Fix checkout action for PR from fork

uui-editor/src/SlateEditor.module.scss, uui-editor/src/SlateEditor.tsx, uui-editor/src/plate/plugins/imagePlugin/ImageBlock.module.scss, uui-editor/src/plate/plugins/imagePlugin/ImageBlock.tsx, uui-editor/todo.md
=> [SlateEditor] Fix caption width

public/docs/content/dataSources-usage-in-components.json, public/docs/content/examples-dataSources-DataSourceViewercode.json
Added description to the DataSourceViewer block.
=> [DataSources Docs]: refactoring completed.

uui-editor/src/plate/plugins/imagePlugin/ImageBlock.module.scss, uui-editor/src/plate/plugins/imagePlugin/ImageBlock.tsx
=> [SlateEditor] Small adjustments

uui-build/config/bundleSizeBaseLine.json
=> Update bundle size baselines

.github/workflows/test.yml
=> Run "build-and-test" job on "pull_request" event from forks.

app/src/docs/_examples/tables/LazyTable.example.tsx, uui-components/src/overlays/Tooltip.tsx, uui/components/tables/DataTableHeaderCell.module.scss, uui/components/tables/DataTableHeaderCell.tsx
=> Feature/DataTable add Tooltip column description#1423

uui-build/linting/eslintrc.base.js
=> remove no-trailing-spaces rule

uui-components/src/pickers/PickerInputBase.tsx
https://github.com/epam/UUI/issues/1324
Reset showSelected state value.
=> [PickerInputBase]: reset 'Show only selected' toggler to the default value #1324

uui-docs/readme.md, uui-editor/readme.md
=> [Docs] Fix mixed readme docs/editor

epam-promo/components/buttons/Button.tsx, epam-promo/components/buttons/LinkButton.tsx, epam-promo/components/layout/IconContainer.tsx, epam-promo/components/overlays/Tooltip.tsx, loveship/components/buttons/Button.tsx, loveship/components/buttons/IconButton.tsx, loveship/components/buttons/LinkButton.tsx, loveship/components/layout/IconContainer.tsx, loveship/components/overlays/Tooltip.tsx, loveship/components/widgets/Badge.tsx
=> put devLogger into if (__DEV__) condition

app/src/demo/tables/filteredTable/columns.tsx
=> Bugfix/RangeDatePicker fixed filter icon in demo/FolteredTable

changelog.md, uui/components/navigation/MainMenu/MainMenuDropdown.module.scss
=> Bugfix/MainMenu no hover#1485

app/src/docs/_examples/contexts/UseUuiServices.example.tsx, app/src/docs/_examples/contexts/UseUuiServicesAdvanced.example.tsx, app/src/docs/_examples/contexts/UseUuiServicesRR6.example.tsx
=> fix examples

changelog.md
=> Add react router 6 warning to the changelog.

changelog.md, epam-promo/components/overlays/DropdownMenu.module.scss, epam-promo/components/overlays/DropdownMenu.tsx, uui/components/overlays/DropdownMenu.module.scss, uui/components/overlays/DropdownMenu.tsx
Issue link(if exists):
https://github.com/epam/UUI/issues/1436
Description:
The height of all buttons in the menu is 36px, the extra pixel is removed in the padding of dropdowns, the menu looks like in the issue layout.
=> Issue 1436

templates/uui-vite-template/README.md
=> Describe tech details of possible solution for UUI template setup.

templates/uui-vite-template/README.md
=> update the description

app/src/demo/tables/filteredTable/columns.tsx, uui/components/overlays/Tooltip.module.scss
=> Bugfix/table column description#1423

epam-promo/components/overlays/DropdownMenu.tsx, uui/components/overlays/DropdownMenu.tsx
Issue link(if exists):
https://github.com/epam/UUI/issues/1436
Description:
Fixed popper's offset for bottom items.
=> issue_1436_commit_fix

uui-editor/src/SlateEditor.tsx, uui-editor/src/helpers.ts, uui-editor/src/plugins/listPlugin/listPlugin.tsx, uui-editor/src/plugins/listPlugin/withList.tsx, uui-editor/src/plugins/separatorPlugin/Separator.tsx, uui-editor/src/plugins/separatorPlugin/separatorPlugin.tsx, uui-editor/todo.md
- fixes focus jumps on list item remove
- fixes splitter removal on ctrl + a then delete scenario
=> [SlateEditor] Fix lists focus jumps

.lintstagedrc.js
=> Prevent commit with eslint warnings

uui-build/linting/eslintrc.base.js
=> Increase severity of no-unused-expressions eslint rule.

.lintstagedrc.js
=> revert max eslint warn changes

uui-core/src/helpers/events.ts
=> Fix issue with parent node lookup

uui-components/src/overlays/PortalRoot.tsx, uui-core/src/services/LayoutContext.ts
=> Make portal root discoverable if it's located in shadow dom.

app/src/docs/_props/epam-promo/components/pickers/common.tsx, app/src/docs/_props/epam-promo/components/pickers/pickerInput.props.tsx, app/src/docs/_props/loveship/components/pickers/common.tsx, app/src/docs/_props/loveship/components/pickers/pickerInput.props.tsx, app/src/docs/_props/uui/components/pickers/common.tsx, app/src/docs/_props/uui/components/pickers/pickerInput.props.tsx, app/src/docs/_props/uui/components/pickers/pickerModal.props.tsx, test-utils/index.ts, test-utils/src/extensions/customQueries.tsx, test-utils/src/testObjects/Picker.ts, test-utils/src/testObjects/PickerList.ts, test-utils/src/testObjects/index.ts, uui-components/src/overlays/ModalBlocker.tsx, uui-components/src/pickers/hooks/types.ts, uui-components/src/pickers/hooks/usePickerList.ts, uui-components/src/pickers/hooks/usePickerListState.ts, uui/components/overlays/__tests__/__snapshots__/ConfirmationModal.test.tsx.snap, uui/components/overlays/__tests__/__snapshots__/Modals.test.tsx.snap, uui/components/pickers/PickerList.tsx, uui/components/pickers/PickerListItem.tsx, uui/components/pickers/__tests__/PickerList.test.tsx, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, uui/components/pickers/__tests__/mocks.ts, uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap
- Added tests for PickerList
- Fixed toggler label
- Fixed maxDefaultItems and maxTotalItems behavior.
=> [PickerList]: tests

draft-rte/tsconfig.json, epam-promo/tsconfig.json, extra/tsconfig.json, loveship/tsconfig.json, test-utils/tsconfig.json, tsconfig.json, tsconfig.test.json, uui-build/linting/eslintrc.base.js, uui-components/tsconfig.json, uui-core/tsconfig.json, uui-db/tsconfig.json, uui-docs/tsconfig.json, uui-editor/tsconfig.json, uui-timeline/tsconfig.json, uui/tsconfig.json
=> Change global patterns in tsconfig to avoid issue with latest webstorm.

app/src/docs/_props/epam-promo/components/overlays/alert.props.tsx, app/src/docs/_props/loveship/components/overlays/alert.props.tsx, changelog.md, epam-assets/theme/theme_loveship.scss, epam-promo/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, loveship/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, public/docs/componentsPropsSet.json, uui/components/overlays/Alert.module.scss, uui/components/overlays/Alert.tsx, uui/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap
=> Bugfix/Alert new design #1517

app/src/docs/_examples/notificationCard/Advanced.example.tsx, app/src/docs/_examples/notificationCard/Basic.example.tsx
#1551 
add alert calls in NotificationCard docs examples
=> [Fix] add alert calls docs examples for NotificationCard component

uui-build/utils/trackBundleSize/trackBundleSize.js
=> Force build of all dependencies.

app/src/common/docs/ComponentEditor.tsx
=> Bugfix/Property Explorer wrap options

epam-promo/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, loveship/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, uui/components/overlays/Alert.tsx, uui/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap
=> [Alert]: fixed LinkButton sizes

app/src/docs/_props/loveship/components/inputs/sliderRating.props.tsx, loveship/components/icons/slider-rating/active_mark_blue_icon.svg, loveship/components/icons/slider-rating/active_mark_green_icon.svg, loveship/components/icons/slider-rating/active_mark_red_icon.svg, loveship/components/icons/slider-rating/active_mark_violet_icon.svg, loveship/components/icons/slider-rating/active_mark_yellow_icon.svg, loveship/components/icons/slider-rating/line_blue_icon.svg, loveship/components/icons/slider-rating/line_red_icon.svg, loveship/components/icons/slider-rating/line_violet_icon.svg, loveship/components/icons/slider-rating/line_yellow_icon.svg, loveship/components/inputs/SliderRating.tsx
=> [SliderRating] Fix colors of icons

uui/components/navigation/MainMenu/Burger/BurgerButton.module.scss
Here is small changes for Burger Button focus state:
=> [Fix] BurgerButton focus styles

uui/components/overlays/Tooltip.tsx
=> [LabeledInput]: fixed default Tooltip color

app/src/docs/Alert.doc.tsx, app/src/docs/_props/uui/components/overlays/alert.props.tsx, app/src/docs/_props/uui/docs/ResizableContext.module.scss, app/src/docs/_props/uui/docs/ResizableContext.tsx, app/src/docs/_props/uui/docs/index.ts, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_loveship_dark.scss, epam-assets/theme/theme_promo.scss, epam-promo/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, loveship/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, public/docs/content/alert-descriptions.json, uui/components/overlays/Alert.module.scss, uui/components/overlays/Alert.tsx, uui/components/overlays/DropdownContainer.module.scss, uui/components/overlays/DropdownContainer.tsx, uui/components/overlays/DropdownMenu.module.scss, uui/components/overlays/DropdownMenu.tsx, uui/components/overlays/__tests__/__snapshots__/Alert.test.tsx.snap, uui/components/overlays/__tests__/__snapshots__/DropdownMenu.test.tsx.snap, uui/components/tables/__tests__/__snapshots__/ColumnHeaderDropdown.test.tsx.snap
=> Themes/color classes & mode classes (Ihor branch)

app/src/sandbox/productsTable/ProductsTableDemo.module.scss, app/src/sandbox/productsTable/ProductsTableDemo.tsx
Fixed infinity extension of a `VirtualList`.
=> [ProductsTableDemo]: fixed infinity extension of a `VirtualList`.

app/src/common/docs/DocExample.module.scss
Fix for this changes https://github.com/epam/UUI/pull/1604
Hovering the title should show link icon.
https://github.com/epam/UUI/assets/11524637/c81a813c-f80c-4b3b-b63a-50e9e4feb300
=> [Fix] icon style

.lintstagedrc.js
=> Don't autofix scss due to the bug in stylelint

.run/Template Jest.run.xml
=> revert config change due to issues in earlier versions of webstorm

app/src/demo/tables/masterDetailedTable/MasterDetailedTable.tsx, uui-components/src/pickers/hooks/usePicker.ts, uui-core/src/data/processing/BaseDataSource.tsx, uui-core/src/data/processing/LazyDataSource.tsx
- Fixed recreation of view at useView on `DataSource` `deps` change.
- Fixed example of Demo table while grouping is changed.
=> [useView]: fixed useView update on DataSource deps change.

app/src/docs/Informer.doc.tsx, app/src/docs/_examples/informer/Basic.example.tsx, app/src/docs/_props/epam-promo/components/widgets/informer.props.tsx, app/src/docs/_props/loveship/components/widgets/informer.props.tsx, app/src/docs/_props/uui/components/widgets/informer.props.tsx, app/src/docs/index.ts, app/src/documents/structure.ts, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_loveship_dark.scss, epam-assets/theme/theme_promo.scss, epam-promo/components/widgets/Informer.tsx, epam-promo/components/widgets/index.ts, loveship/components/widgets/Informer.tsx, loveship/components/widgets/index.ts, public/docs/content/examples-informer-Basic.json, public/docs/content/informer-descriptions.json, uui-docs/src/editors/ColorPicker.tsx, uui/components/widgets/Informer.module.scss, uui/components/widgets/Informer.tsx, uui/components/widgets/index.ts
=> [Informer]: created new component. With demo and PE in all skins

app/src/docs/_props/uui/components/overlays/alert.props.tsx, epam-assets/theme/theme_loveship_dark.scss, uui/components/buttons/LinkButton.module.scss, uui/components/layout/Accordion.module.scss
=> [Accordion]: fixed disabled icon color, [Alert]: fixed darkTheme colors

changelog.md
https://github.com/epam/UUI/issues/1589
https://github.com/epam/UUI/issues/1593
Added what was done in the scope of these tickets to the change log.
=> fix: added to changes to change log

uui-build/rollup/rollup.config.js
=> Fix issues with non-unique IDs of SVG.

app/src/docs/_examples/richTextEditor/Serialization.example.tsx, uui-editor/src/plugins/iframePlugin/iframePlugin.tsx, uui-editor/src/plugins/uploadFilePlugin/file_uploader.ts
Adds upload callback for serialization example.
=> [SlateEditor] Add upload plugin for serialization example

app/src/sandbox/SandboxPage.tsx, app/src/sandbox/forms/TagInput.tsx, changelog.md, public/docs/content/examples-accordion-Custom.json, public/docs/content/pickerInput-descriptions.json, uui-components/src/pickers/KeyboardUtils.tsx, uui-components/src/pickers/PickerBodyBase.tsx, uui-components/src/pickers/PickerToggler.tsx, uui-components/src/pickers/hooks/types.ts, uui-components/src/pickers/hooks/usePicker.ts, uui-components/src/pickers/hooks/usePickerInput.ts, uui-core/src/helpers/IEditableDebouncer.ts, uui/components/filters/FilterPanelItemToggler.module.scss, uui/components/pickers/DataPickerBody.tsx, uui/components/pickers/PickerInput.tsx, uui/components/pickers/PickerModal.tsx, uui/components/pickers/__tests__/PickerInput.test.tsx
=> Picker input keyboard improvements

app/src/demo/tables/masterDetailedTable/FilterPanel/FilterPanel.tsx, app/src/demo/tables/masterDetailedTable/FilterPanel/GroupingBlock/GroupingBlock.tsx, app/src/demo/tables/masterDetailedTable/useLazyDataSourceWithGrouping/groupingConfigBuilder.ts, app/src/demo/tables/masterDetailedTable/useLazyDataSourceWithGrouping/types.ts, app/src/demo/tables/masterDetailedTable/useLazyDataSourceWithGrouping/useLazyDataSourceWithGrouping.ts
Fixed switch between groups while some element is checked.
=> [Demo table]: Fix grouping switch with checked elements.

app/src/demo/tables/masterDetailedTable/FilterPanel/FiltersBlock/Filter/Filter.tsx
Fixed changing of filter with grouping.
=> [Demo Table]: fixed changing of filter with grouping.

app/src/demo/tables/masterDetailedTable/FilterPanel/FilterPanel.tsx
Commented out not working panels.
=> [Demo Table]: Commented out not working panels.

app/src/demo/tables/editableTable/columns.tsx
Fixed status column UI.
https://github.com/epam/UUI/assets/22456368/27affdc2-1116-4899-b7e9-5f3e9ae631e1
=> [EditableTable Demo]: fixed status column

app/src/docs/_examples/tables/TableWithPinnedRows.example.tsx, app/src/docs/tables/Advanced.doc.tsx, public/docs/content/examples-tables-TableWithPinnedRows.json
Added advanced example of configuring tables with pinned rows.
=> [PinnedRows in Tables]: added example of pinned rows in tables.

uui-core/src/data/processing/views/LazyListView.ts
Fixed plain check of nested parents.
=> [LazyListView]: Fixed cascade selection explicit plain parent check.

app/src/docs/_examples/tables/PresetsPanelBasic.example.tsx, uui-core/src/hooks/useTableState/__tests__/useTableState.test.tsx, uui-core/src/hooks/useTableState/useTableState.ts, uui-core/src/types/props.ts
#1610
#1601
- Adds confirmation modal for presets example.
- Change `validationMessageType` for `LabeledInput`
=> [PresetsPanel] Add modal example for presets

app/src/demo/dnd/DndCriterion.tsx, app/src/demo/dnd/DndSection.module.scss, app/src/demo/dnd/DndSection.tsx
https://github.com/epam/UUI/issues/1435
=> [Dnd] prevent click on draggable element

epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_promo.scss
[Button]: fixed text color (neutral, secondary colors, fill - outline, none, ghost), fixed focus.
=> [Button]: fixed issues

uui-core/src/services/routing/Router6AdaptedRouter.ts
#1708
Fix disacard form navigation
=> [Router] Fix discard form navigation

changelog.md, uui-components/src/pickers/hooks/usePickerInput.ts
Fix picker input scroll for mobile.
=> [Picker Input] Fix picker input scroll for mobille

changelog.md, uui-components/src/inputs/TextArea.tsx, uui-components/src/inputs/TextInput.tsx
#1470
Fix `maxLength` for Android.
=> [TextArea][TextInput] Fix max length for Android

app/src/common/docs/BaseDocsBlock.module.scss, app/src/common/docs/BaseDocsBlock.tsx, app/src/common/docs/EditableDocContent.module.scss
=> Set promo theme for Docs

app/src/docs/_examples/countIndicator/Basic.example.tsx, epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_loveship_dark.scss, epam-assets/theme/theme_promo.scss, uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerToggler.test.tsx.snap, uui/components/widgets/Tag.tsx, uui/components/widgets/__tests__/__snapshots__/Tag.test.tsx.snap
=> [CountIndicator, Tag]: fixed gray color

changelog.md, uui/components/pickers/DataPickerFooter.tsx, uui/components/pickers/PickerModal.tsx, uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap
Added zero rows checker in PickerFooter
=> [Pickers]: "Select all" option available without values #1729

changelog.md, uui-components/src/buttons/ButtonBase.tsx, uui-components/src/navigation/Anchor.tsx, uui/components/fileUpload/__tests__/__snapshots__/DropSpot.test.tsx.snap, uui/components/navigation/__tests__/__snapshots__/Anchor.test.tsx.snap, uui/components/overlays/DropdownMenu.tsx
=> [DropdownMenuButton] Fix `isActive`

app/src/docs/_props/uui/components/pickers/common.tsx, epam-assets/theme/theme_loveship_dark.scss, uui/components/datePickers/DatePickerBody.module.scss, uui/components/datePickers/RangeDatePicker.module.scss, uui/components/inputs/Slider.module.scss, uui/components/inputs/Slider.tsx, uui/components/inputs/Switch.module.scss, uui/components/inputs/__tests__/__snapshots__/Slider.test.tsx.snap, uui/components/pickers/DataPickerRow.module.scss, uui/components/widgets/IndeterminateBar.module.scss, uui/components/widgets/ProgressBar.module.scss, uui/components/widgets/StatusIndicator.module.scss
…xed selected year/month bg color, [RangeDatePicker]: fixed error border color, [Slider]: fixed tooltip & caption colors, [Switch]: fixed toggler and border colors, [ProgressBar]: fixed border-radius, [StatusIndicator]: fixed 24size font-weight.
=> themes fixPack

public/docs/content/unitTestingGuide-2-cookbook.json, uui/components/filters/__tests__/filtersPanel.test.tsx, uui/components/pickers/__tests__/PickerInput.test.tsx, uui/components/pickers/__tests__/PickerList.test.tsx, uui/components/pickers/__tests__/PickerModal.test.tsx, uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap
=> Add 'react-focus-lock' mock to all tests where it's needed.

app/src/common/docs/BaseDocsBlock.tsx, app/src/docs/_examples/richTextView/Basic.example.tsx, app/src/docs/_props/epam-promo/components/inputs/searchInput.props.ts, app/src/docs/_props/epam-promo/components/widgets/badge.props.tsx, app/src/docs/_props/loveship/components/inputs/searchInput.props.ts, app/src/docs/_props/loveship/components/widgets/badge.props.tsx, app/src/docs/_props/uui/components/inputs/searchInput.props.ts, epam-promo/components/widgets/Badge.tsx, loveship/components/widgets/Badge.tsx
…RTV]: deleted unuseful icons, [SearchInput]: added mode in PE, [Badge]: added 'mint' & 'cyan' colors
=> bugs FixPack 10 Nov

uui-components/src/table/columnsConfigurationModal/columnsConfigurationUtils.ts, uui-components/src/table/columnsConfigurationModal/types.ts
Fix checkbox appear in right column
=> [DataTable] Fix checkbox appear in right column

uui-core/src/data/processing/ArrayDataSource.tsx, uui-core/src/data/processing/AsyncDataSource.tsx, uui-core/src/data/processing/BaseDataSource.tsx, uui-core/src/data/processing/LazyDataSource.tsx, uui-core/src/data/processing/views/ArrayListView.ts
Fixed reload of data at AsyncDataSource if deps were changed. Also, the native reload functionality was fixed.
=> [AsyncDataSource]: Fixed reload async ds on deps change.

app/src/docs/_examples/form/FormLeaveHandling.example.tsx, app/src/docs/_examples/modals/ModalWithForm.example.tsx, uui-core/src/data/forms/__tests__/useForm.test.tsx, uui-core/src/data/forms/useForm.ts, uui-core/src/data/forms/useLock.ts, uui/components/forms/Form.tsx, uui/components/forms/useForm.tsx, uui/components/tables/columnsConfigurationModal/ColumnRow.module.scss
#1531
Get rid of lock context for forms.
=> [Form] Get rid of lock context for forms

app/src/docs/richTextView/richTextViewExamples.tsx
=> Fix example of rte

uui-docs/src/editors/shared/numEditor.tsx
=> Hide value because it's already shown in Num input.

changelog.md, uui/components/datePickers/Calendar.module.scss
=> [Calendar]: fixed disabled text token

app/src/common/AppHeader.module.scss, app/src/common/AppHeader.tsx
=> [ThemeSwitcher]: remade by new design

changelog.md, uui/components/typography/Text.module.scss
Fixed wrong colors for skins, fixed colors for semantic colors(info, warning, error, success)
=> [Text]: color fix

epam-assets/theme/theme_loveship_dark.scss
=> [Tag dark theme]: fixed additional colors

changelog.md, uui-core/src/data/processing/views/LazyListView.ts
Enabled showing placeholders on cache clearing in LazyDataSource.
=> [LazyDataSource]: fixed reload on clearing cache.

uui-components/src/table/columnsConfigurationModal/__tests__/columnsConfigurationUtils.test.tsx, uui-components/src/table/columnsConfigurationModal/columnsConfigurationUtils.ts
Fixes #1800
Fixes pinned right columns
=> [Table] Fix pinned right table columns

uui-editor/src/migration.ts
=> [Editor] Fix schema migration

.github/workflows/qualityGateCommentPR.yml
=> Minor fix of MD markup

public/docs/docsGenOutput/docsGenOutput.json, uui-build/docsGen/__tests__/__snapshots__/docsGenUnion.test.ts.snap, uui-build/docsGen/compareStatsUtils/statsMdFormatterUtils.ts, uui-build/docsGen/converters/converterForProps.ts
=> Improve prop uid generation

.github/workflows/qualityGateCommentPR.yml
=> Improve quality gate workflow

.github/workflows/qualityGateCommentPR.yml
=> Small fix in qualityGateCommentPR

epam-assets/theme/theme_loveship.scss
=> [Button]: hotfix for loveship white button in fill-none & fill-ghost

.github/workflows/qualityGate.yml, uui-build/ts/docsGen/compareStatsUtils/statsMdFormatterUtils.ts
=> Fix cache in qualityGate workflow

uui-editor/src/SlateEditor.tsx
=> [SlateEditor] Enable onBlur and pnKeyDown callbacks

epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_loveship_dark.scss
=> [Button]: fixed white color fill ghost hover state styles

uui-editor/src/SlateEditor.tsx
=> [SlateEditor] Fix toolbar appearing

app/src/common/docs/componentEditor/view/PropSamplesCreationContext.tsx, uui-docs/src/docBuilderGen/docBuilderGen.tsx, uui-docs/src/docBuilderGen/docBuilderGenTypes.ts, uui-docs/src/docBuilderGen/hooks/useDocBuilderGen.tsx, uui-docs/src/docBuilderGen/propDetailsBuilders/build.tsx, uui-docs/src/docBuilderGen/propDetailsBuilders/buildByEditorType.tsx, uui-docs/src/docBuilderGen/propDetailsBuilders/buildByPropFromRef.tsx, uui-docs/src/docBuilderGen/propDetailsBuilders/buildByPropName.tsx, uui-docs/src/docBuilderGen/propDetailsBuilders/shared/reusableExamples.tsx, uui-docs/src/types.ts
=> Change callback prop auto-generate for better support of Union types.

app/src/sandbox/tokens/palette/components/paletteTable/tableColumns.tsx, app/src/sandbox/tokens/palette/types/types.ts
=> Fix jumping column

uui-docs/src/demoData/slateInitialValue.ts, uui-editor/src/__tests__/__snapshots__/migration.test.ts.snap, uui-editor/src/__tests__/data.ts, uui-editor/src/__tests__/migration.test.ts, uui-editor/src/migration.ts, uui-editor/src/plugins/tablePlugin/TableCellElement.tsx, uui-editor/src/plugins/tablePlugin/tablePlugin.tsx, uui-editor/src/plugins/tablePlugin/types.ts
- Consider colSpan & rowSpan from the old `data` object
- Adjust table example with merged cells
=> [SlateEditor] Fix colspan / rowspan & add merged cells to example

uui-components/src/inputs/NumericInput.tsx, uui-components/src/inputs/__tests__/NumericInput.test.tsx, uui-core/src/helpers/__tests__/numericInputCalculations.test.tsx, uui-core/src/helpers/numericInputCalculations.ts
- Fixes #1860
- Improves null checks
=> [NumericInput] Improve placeholder

changelog.md, uui-components/src/overlays/DropdownContainer.tsx, uui-core/src/types/tables.ts, uui/components/filters/FilterPickerBody.tsx, uui/components/filters/FiltersPanelItem.tsx, uui/components/overlays/__tests__/__snapshots__/DropdownContainer.test.tsx.snap, uui/components/overlays/__tests__/__snapshots__/DropdownMenu.test.tsx.snap, uui/components/pickers/MobileDropdownWrapper.tsx, uui/components/tables/__tests__/__snapshots__/ColumnHeaderDropdown.test.tsx.snap
=> * [FiltersPanel]: added 'maxBodyHeight' prop for picker filters

uui-editor/src/plugins/linkPlugin/AddLinkModal.tsx
=> [SlateEditor] Fix link update

uui-editor/src/plugins/videoPlugin/AddVideoModal.tsx
=> [SlateEditor] Fix iframe loading

app/src/demo/tables/editableTable/ProjectTableDemo.tsx, app/src/demo/tables/editableTable/helpers.ts
Closes: https://github.com/epam/UUI/issues/1896
Removed deleting of the last item if none is selected.
=> [ProjectTableDemo]: Removed deleting of the last item if none is selected.

uui-editor/src/plugins/linkPlugin/AddLinkModal.tsx
Return initial link value in modal.
=> [SlateEditor] Return initial link value

uui-components/src/overlays/ModalBlocker.tsx, uui-components/src/pickers/hooks/usePickerInput.ts
#1792
fixes overflow 
- when dropdown in modal 
- when modal in modal
=> [Modals] Fix overflow when dropdown modal

app/src/sandbox/tokens/docs/config.ts, app/src/sandbox/tokens/docs/types.ts, app/src/sandbox/tokens/docs/useTokensDoc.tsx, app/src/sandbox/tokens/palette/components/paletteTable/paletteTable.tsx, app/src/sandbox/tokens/palette/components/paletteTable/tableColumns.tsx, app/src/sandbox/tokens/palette/constants.ts, app/src/sandbox/tokens/palette/hooks/useThemeTokens/loadedTokensConverter.ts, app/src/sandbox/tokens/palette/types/sharedTypes.ts, app/src/sandbox/tokens/palette/types/types.ts, public/docs/figmaTokensGen/ThemeTokens.json, uui-build/ts/tasks/themeTokensGen/types/sharedTypes.ts, uui-build/ts/tasks/themeTokensGen/utils/figmaVarUtils.ts
=> Expose "published" column in tokens table

app/src/docs/assets/loveship/LoveshipColorsDoc.module.scss, app/src/docs/assets/promo/PromoColorsDoc.module.scss, epam-assets/scss/loveship/colors.scss, epam-assets/scss/promo/colors.scss, epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_promo.scss
=> fixed some colors by design

epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_promo.scss
=> tuned yellow & cyan token colors by design

epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_promo.scss
=> fixed yellow-70 color by design

uui-build/ts/tasks/docsGen/tsdoc/tsDocUtils.ts
=> Support windows style line breaks in docs gen

uui-build/ts/tasks/docsGen/tsdoc/__tests__/tsDocUtils.test.ts, uui-build/ts/tasks/docsGen/tsdoc/tsDocFormatters.ts, uui-build/ts/tasks/docsGen/tsdoc/tsDocTags.ts, uui-build/ts/tasks/docsGen/tsdoc/tsDocUtils.ts, uui-build/ts/tasks/docsGen/types/sharedTypes.ts, uui-docs/src/docsGen/sharedTypes.ts
=> Support @deprecated tag in DocsGen

uui-build/ts/tasks/themeMixinsGen/constants.ts, uui-build/ts/tasks/themeMixinsGen/utils/tokenFormatters.ts
=> Adjust formatter

.github/workflows/base.yml, .github/workflows/qualityGate.yml, .github/workflows/test.yml
=> Update Node version on CI: 16 -> 18

app/src/common/docs/componentEditor/view/peTable/PeTableRow.tsx, app/src/docs/_examples/modals/ModalWithForm.example.tsx, app/src/docs/_examples/radioInput/Group.example.tsx, app/src/sandbox/forms/PersonDetailEditor.tsx, app/src/sandbox/forms/PersonDetailView.tsx, app/src/sandbox/scroll-spy/ScrollSpyForm.tsx, app/src/sandbox/theme-electric-test/ThemeDemo.tsx, app/src/sandbox/theme/ThemeDemo.tsx, app/src/sandbox/tokens/palette/components/paletteTable/tableColumns.tsx, changelog.md, public/docs/content/examples-radioInput-Group.json, public/docs/content/radioGroup-descriptions.json, public/docs/docsGenOutput/docsGenOutput.json, uui-components/src/inputs/RadioInput.tsx, uui-docs/src/peContexts/FormContext.tsx, uui-docs/src/peEditors/examples/singleUnknownExample.tsx, uui/components/inputs/TextInput.tsx, uui/components/layout/RadioGroup.tsx
=> Bugfix/PE fixed RadioInput behaviour#701

app/src/docs/Text.doc.tsx, app/src/docs/_examples/dropdown/CloseFromBody.example.tsx, app/src/docs/_examples/dropdownContainer/Basic.example.tsx, app/src/docs/_examples/pickerInput/ConfigurePortalTargetAndPlacement.example.tsx, app/src/docs/_examples/scrollSpy/BasicScrollSpy.example.tsx, app/src/docs/_examples/text/Basic.example.tsx, changelog.md, epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_loveship_dark.scss, epam-assets/theme/theme_promo.scss, epam-assets/theme/theme_vanilla_thunder.scss, public/docs/docsGenOutput/docsGenOutput.json, uui/components/filters/FilterPanelItemToggler.module.scss, uui/components/filters/FilterPanelItemToggler.tsx, uui/components/filters/__tests__/__snapshots__/filtersPanel.test.tsx.snap, uui/components/navigation/MainMenu/Burger/Burger.module.scss, uui/components/typography/Text.module.scss, uui/components/typography/Text.tsx
=> Bugfix/remove uui-text-brand#1941

changelog.md, uui/components/overlays/Tooltip.module.scss
=> Bugfix/tooltip fixed vertical paddings#1939

uui-build/ts/tasks/docsGen/__tests__/__snapshots__/docsGenComments.test.ts.snap, uui-build/ts/tasks/docsGen/__tests__/__snapshots__/docsGenComplexTypes.test.ts.snap, uui-build/ts/tasks/docsGen/__tests__/__snapshots__/docsGenIntersection.test.ts.snap, uui-build/ts/tasks/docsGen/__tests__/__snapshots__/docsGenMappedType.test.ts.snap, uui-build/ts/tasks/docsGen/__tests__/__snapshots__/docsGenPropEditor.test.ts.snap, uui-build/ts/tasks/docsGen/__tests__/__snapshots__/docsGenUnion.test.ts.snap
=> Fix docs gen test snapshots in main branch

app/src/common/docs/componentEditor/view/ComponentEditorView.tsx, app/src/common/docs/componentEditor/view/peTable/PeTable.tsx, app/src/common/docs/componentEditor/view/peTable/types.ts
=> Sort props in prop editor alphabetically.

uui-docs/src/demoData/slateSerializationInitialData.ts
Fixes #1968
Fix links in html format example.
=> [SlateEditor] Fix links in html format example

uui-core/src/data/processing/views/BaseListView.tsx
=> [DataSources]: Fixed some child selected.

uui-core/src/data/processing/views/ArrayListView.ts, uui-core/src/data/processing/views/LazyListView.ts, uui-core/src/data/processing/views/tree/BaseTree.ts, uui-core/src/data/processing/views/tree/EditableTree.ts, uui-core/src/data/processing/views/tree/ITree.ts
Fixed clearing of all items before opening PickerInput body.
=> [PickerInput]: Fixed "Clear all" before PickerInput body opening.

app/src/docs/themes/Overview.tsx, app/src/docs/themes/Tokens.tsx, app/src/docs/themes/implementation/TokenGroups.tsx, app/src/docs/themes/index.ts, app/src/documents/structure.ts, public/docs/content/Tokens-intro.json
=> [Tokens page]: design-review fixes.

epam-assets/theme/theme_loveship_dark.scss
=> [Badge]: fixed color600 outline tokens for dark theme

uui/components/inputs/timePicker/TimePicker.tsx
=> [TimePicker]: fixed clear time 

uui-editor/src/migration.ts, uui-editor/src/plugins/linkPlugin/AddLinkModal.tsx
- improve migration for old tables
- allow adding any links
=> [SlateEditor] Improve migration for old tables & allow any links

app/src/docs/_examples/tables/TableCollapse.example.tsx
Removed filter from TableCollapse example.
=> [DataTable]: removed filter from example.

uui-core/src/data/processing/__tests__/arrayDataSource.test.ts, uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.bad-child-counts.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.complex-ids.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.duplicated-records.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.flat.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.old.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree-no-counts.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree-search.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree.test.ts, uui/components/pickers/__tests__/DataPickerBody.test.tsx
Moved tests to `useView` usage.
=> [DataSources]: Tests to useView usage.

uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/LazyListView.ts
Added fetching data on search clear in `LazyDataSources`.
=> [LazyListView]: refetch on search clear.

templates/uui-nextjs-template/template/package.json
=> Fix nextjs dependencies

uui-editor/package.json, yarn.lock
=> Fix issues with uui-editor dependencies

uui-components/src/table/columnsConfigurationModal/columnsConfigurationUtils.ts, uui-components/src/table/columnsConfigurationModal/hooks/useColumnsConfiguration.ts, uui/components/tables/columnsConfigurationModal/ColumnsConfigurationModal.tsx
…e selected columns 2) search is not working for pinned-right columns.
=> [ColumnsConfigurationModal] fix some bugs

app/src/docs/_examples/pickerList/Basic.example.tsx, uui-core/src/data/processing/AsyncDataSource.tsx, uui-core/src/data/processing/views/AsyncListView.ts
Fixes bug at https://codesandbox.io/p/sandbox/uui-kw8fcj?file=%2FExample.tsx.
=> [AsyncDataSource]: fixed updating of the view after data loading.

uui-core/src/data/processing/ListApiCache.tsx, uui-core/src/data/processing/views/ArrayListView.ts, uui-core/src/data/processing/views/BaseListView.tsx, uui-core/src/data/processing/views/LazyListView.ts, uui-core/src/data/processing/views/tree/EditableTree.ts
Added possibility to clear unknown records with "clear all" and "clear" of a specific tag.
https://github.com/epam/UUI/assets/22456368/1205bfdc-4aad-44aa-8330-0d4c30379365
https://github.com/epam/UUI/assets/22456368/b803aac1-f8b1-416c-bb7d-06612a7c311f
https://github.com/epam/UUI/assets/22456368/5f195f31-496b-40dd-a977-a7ac9a392d70
https://github.com/epam/UUI/assets/22456368/b09b056f-7b0f-48f1-80f9-bf698bc4906e
https://github.com/epam/UUI/assets/22456368/deec73c8-f58c-488e-bd67-5fb64185ae8c
https://github.com/epam/UUI/assets/22456368/790bb90d-7c8c-4c5c-b4ef-bca9d0e00b24
=> [DataSources]: clear unknown records added.

epam-assets/theme/theme_electric.scss, epam-assets/theme/theme_loveship.scss, epam-assets/theme/theme_loveship_dark.scss, epam-assets/theme/theme_promo.scss, epam-electric/components/widgets/Badge.tsx, public/docs/docsGenOutput/docsGenOutput.json
=> Bugfix/Badge improvements #1990

app/src/sandbox/tokens/palette/types/sharedTypes.ts, app/src/sandbox/tokens/palette/utils/themeVarUtils.ts, public/docs/figmaTokensGen/Theme.json, public/docs/figmaTokensGen/ThemeOutput.json, public/docs/figmaTokensGen/ThemeTokens.json, uui-build/ts/tasks/themeMixinsGen/constants.ts, uui-build/ts/tasks/themeTokensGen/types/sharedTypes.ts
=> Update theme names to match Figma modes

uui-components/package.json, uui-components/src/buttons/IconButton.tsx, uui/components/buttons/IconButton.tsx, uui/components/filters/PresetPanel/__tests__/__snapshots__/Preset.test.tsx.snap, uui/components/filters/PresetPanel/__tests__/__snapshots__/PresetActionsDropdown.test.tsx.snap
=> Bugfix/IconButton is dropdown prop not work #1976

uui/components/fileUpload/DropSpot.module.scss, uui/components/filters/PresetPanel/Preset.module.scss, uui/components/filters/PresetPanel/PresetActionsDropdown.module.scss, uui/components/filters/PresetPanel/PresetActionsDropdown.tsx, uui/components/filters/PresetPanel/__tests__/__snapshots__/Preset.test.tsx.snap, uui/components/filters/PresetPanel/__tests__/__snapshots__/PresetActionsDropdown.test.tsx.snap, uui/components/layout/LabeledInput.module.scss
…ponent icon sizes, [Preset]: fixed preset button layout
=> [LabeledInput]: fixed inner icon styles, [Preset]: fixed preset button layout

uui/components/pickers/PickerList.module.scss, uui/components/pickers/PickerList.tsx, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap
=> [PickerList]: fixed caption align

uui-core/src/data/processing/views/LazyListView.ts
Fixed an issue with modification of response in LazyListView, if the response is frozen.
=> [LazyListView]: Removed modification of response in LazyListView.

changelog.md, epam-promo/i18n.ts, uui/components/fileUpload/FileCard.tsx, uui/i18n.ts
Not all strings in the FileCard component moved to the translation file. This will give more flexibility for multilanguage websites that will need to translate everything.
=> Filecard component i18n translation

app/src/docs/_examples/richTextEditor/MdSerialization.example.tsx, uui-docs/src/demoData/slateMdSerializationInitialData.ts, uui-editor/package.json, uui-editor/src/md-serializer/serialize.ts, uui-editor/src/md-serializer/types.ts, uui-editor/src/plugins/colorPlugin/colorPlugin.tsx, uui-editor/src/plugins/deserializeMdPlugin/deserializeMdPlugin.ts, uui-editor/src/serialization.ts, yarn.lock
Adds suport of
- `<br>` break line
- improves lists
=> [SlateEditor] Improve lists for md

uui-editor/src/plugins/imagePlugin/ImageBlock.tsx, uui-editor/src/plugins/imagePlugin/ImageElement.tsx
=> [SlateEditor] Fix image readonly

uui-e2e-tests/package.json, uui-e2e-tests/scripts/envFileUtils.ts
=> Fix package version

.github/workflows/e2e.yml
=> Run e2e tests on push to develop

package.json, uui-e2e-tests/package.json, uui-e2e-tests/readme.md
=> Adjust docs. Rename some tasks related to e2e.

uui-e2e-tests/readme.md
=> Update e2e docs

uui-components/src/inputs/Slider/Slider.tsx, uui-components/src/inputs/Slider/SliderBase.tsx, uui-components/src/inputs/Slider/SliderScaleBase.tsx, uui-components/src/inputs/__tests__/Slider.test.tsx
=> [Slider]: fixed floating number point problem, like 0.1 + 0.2

uui-core/src/data/processing/ArrayDataSource.tsx
Fixed initialization of itemsStorage in ArrayDataSource.
=> [ArrayDataSource]: Fixed initialization of items storage appropriately.

uui/components/widgets/StatusIndicator.module.scss
=> Feature/StatusIndicator improve by design #2122

uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLoadData.ts
Fixed problem with ref === undefined and call .then on it.
=> [useLazyTree]: fixed problem with ref.

uui-e2e-tests/readme.md
=> Adjust docs

uui-core/src/data/lenses/lensesImpl.tsx
Reused code from `getMetadata` and `getValidationState`.
=> [ILensImpl]: refactored lens impl

app/src/docs/_examples/pickerInput/GetRowOptions.example.tsx
Fixed logic for disabled checkboxes in example.
=> [PickerInput]: getRowOptions isDisabled example fixed.

uui-components/src/layout/Accordion.tsx
=> Bugfix/Accordion space focus#705

uui-components/src/pickers/hooks/usePicker.ts, uui-components/src/pickers/hooks/usePickerInput.ts, uui-components/src/pickers/hooks/usePickerListState.ts, uui-components/src/pickers/hooks/usePickerModal.ts, uui/components/pickers/PickerModal.tsx
Fixed clearing search on show only selected toggling and vice verse in PickerModal.
=> [PickerModal]: fixed clearing show only selected on search change and vice verse.

uui-core/src/types/components/DatePicker.ts, uui/components/datePickers/DatePicker.tsx, uui/components/datePickers/RangeDatePicker.tsx
Fixed DatePicker and RangePicker refs.
=> [EditableTables]: fixed DatePicker and RangePicker refs

uui-e2e-tests/playwright.config.ts, uui-e2e-tests/scripts/constants.ts, uui-e2e-tests/scripts/envFileUtils.ts, uui-e2e-tests/src/types.ts, uui-e2e-tests/src/utils/ctx.ts, uui-e2e-tests/src/utils/testBuilder.ts
=> Fix some issues

uui-components/src/pickers/hooks/usePicker.ts, uui-components/src/pickers/hooks/usePickerInput.ts, uui-core/src/hooks/index.ts, uui-core/src/hooks/usePrevious.ts, uui-core/src/types/pickers.ts, uui/components/filters/FilterPickerBody.tsx, uui/components/filters/FiltersPanel.tsx, uui/components/pickers/PickerInput.tsx, uui/components/pickers/__tests__/PickerModal.test.tsx
Fixed working with dataSourceState updates and all bugs, related to dataSourceState pinning and warnings.
=> [Pickers]: fixed working with dataSourceState updates.

public/docs/docsGenOutput/docsGenOutput.json, uui-components/src/inputs/RadioInput.tsx, uui-components/src/inputs/Switch.tsx, uui-components/src/inputs/TextArea.tsx, uui-components/src/layout/Accordion.tsx, uui-components/src/layout/ControlGroup.tsx, uui-core/src/types/components/Checkbox.ts, uui-core/src/types/components/LabeledInput.tsx
=> Removed forwardedRef from FC

app/src/demo/tables/editableTable/ProjectTableDemo.tsx
Prevented moving parents into children
=> [ProjectTableDemo]: Prevented rows from dnd parent into child

app/src/common/AppHeader.tsx, app/src/common/docs/componentEditor/ComponentEditor.tsx, app/src/common/docs/componentEditor/utils.ts, app/src/data/appContext.ts, app/src/data/themes.ts, app/src/index.tsx, app/src/preview/previewContent/previewContent.tsx, uui-build/ts/tasks/docsGen/converters/converterUtils/propEditorUtils.ts, uui-docs/src/docBuilderGen/docBuilderGen.tsx, uui-docs/src/docBuilderGen/docBuilderGenTypes.ts, uui/components/datePickers/__tests__/__snapshots__/DatePicker.test.tsx.snap, uui/components/datePickers/__tests__/__snapshots__/RangeDatePicker.test.tsx.snap, uui/components/filters/PresetPanel/__tests__/__snapshots__/PresetInput.test.tsx.snap, uui/components/inputs/__tests__/__snapshots__/NumericInput.test.tsx.snap, uui/components/inputs/__tests__/__snapshots__/TextInput.test.tsx.snap, uui/components/inputs/__tests__/__snapshots__/TimePicker.test.tsx.snap, uui/components/inputs/__tests__/__snapshots__/__snapshots__/TimePicker.test.tsx.snap, uui/components/layout/__tests__/__snapshots__/LabeledInput.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/DataPickerBody.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap
=> Allow overriding props via settings.json

app/src/demo/tables/editableTable/ProjectTableDemo.tsx, app/src/demo/tables/editableTable/columns.tsx, app/src/demo/tables/editableTable/helpers.ts, app/src/demo/tables/editableTable/types.ts, uui-core/src/data/processing/views/tree/helpers/patch.ts, uui-core/src/data/processing/views/tree/hooks/common/usePatchTree.ts
- Fixed moving between parents in patch with fixPatchBeetweenSortings = false
- Refactored ProjectDemp
=> [useTree]: fixed moving between parents in patch with fixPatchBetweenSortings = false and refactored ProjectDemo.

uui-core/src/data/processing/views/tree/treeStructure/helpers/FetchingHelper.ts, uui-docs/src/commonDocs/pickerDocs.tsx
- fixed handling null items as search results;
-  and fixed Pickers lazy explorer.
=> [useLazyTree]: fixed handling null items as search result and fixed Pickers lazy explorer.

.github/workflows/e2e.yml, uui-e2e-tests/e2e.Dockerfile, uui-e2e-tests/package.json, yarn.lock
=> Upgrade Playwright to 1.43.1

.github/workflows/qa.yml
=> Deploy "feature/sizes-customizing" to QA

app/src/demo/tables/filteredTable/filters.tsx, uui-core/src/types/tables.ts, uui/components/filters/FilterPickerBody.tsx
Added highlightSearchMatches to filters.
=> [Filters]: Added highlightSearchMatches to filters.

public/docs/figmaTokensGen/ThemeTokens.json, uui-build/ts/tasks/themeTokensGen/utils/sortingUtils.ts
=> [Tokens page]: returned tokens sorting by abc

app/src/data/apiDefinition.ts, app/src/demo/form/DemoForm.tsx, app/src/demo/form/validationShema.ts, app/src/demo/tables/filteredTable/FilteredTable.tsx, app/src/docs/_examples/form/ServerValidation.example.tsx, changelog.md, server/api/form.js, server/api/index.js, test-utils/src/mocks/TestStubAdaptedRouter.ts, test-utils/src/rendering/renderingWithContextUtils.tsx, uui-core/src/data/forms/Form.tsx, uui-core/src/data/forms/__tests__/useForm.test.tsx, uui-core/src/data/forms/useForm.ts, uui-core/src/data/forms/useLock.ts, uui-core/src/data/validation/validate.ts
=> Form impovements

uui-e2e-tests/playwright.config.ts
=> Optimize e2e config for local dev

uui-editor/package.json, uui-editor/src/SlateEditor.tsx, uui-editor/src/defaultPlugins.ts, uui-editor/src/implementation/PositionedToolbar.tsx, uui-editor/src/implementation/StickyToolbar.tsx, uui-editor/src/plugins/eventEditorPlugin/eventEditorPlugin.ts, uui-editor/src/plugins/tablePlugin/MergeToolbarContent.tsx, uui-editor/src/plugins/tablePlugin/ToolbarContent.tsx, yarn.lock
Fixes https://github.com/epam/UUI/issues/2088
- Improve editor focus
- Add memoization
- Update plate to fix warn on `serializeHtml`
=> [PlateEditor] Improve editor focus

app/src/common/docs/componentEditor/view/fullscreenBtn/fullscreenBtn.tsx, app/src/docs/pickerInput/PickerInput.doc.tsx, app/src/preview/types.ts, app/src/preview/utils/previewLinkUtils.ts, uui-docs/src/DocBuilder.ts, uui-docs/src/types.ts
=> Improve list of preview rendering in prop explorer

app/src/docs/_examples/controlGroup/Prefix.example.tsx, changelog.md, uui/components/datePickers/RangeDatePicker.module.scss, uui/components/layout/ControlGroup.module.scss, uui/components/pickers/PickerToggler.module.scss
=> [ControlGroup & RangeDatePicker]: made flat shared border

uui/components/overlays/Modals.module.scss
=> [Modals]: fixed border-radius

uui/components/inputs/timePicker/TimePicker.module.scss
=> Bugfix/TimePicker dots color#2249

app/src/docs/_examples/contexts/NotificationContext.example.tsx
Fixed unknown in NotificationContext example.
=> [NotificationContextExample]: fixed unknown.

app/src/common/AppHeader.tsx, app/src/docs/pickerInput/pickerInputExamples.tsx
[AppHeader]: added width to the img to avoid cache problem
[AppHeader]: added width to the img to avoid cache problem
=> [PickerInput]: fixed example into PE mode: multi, renderTag prop.

uui-editor/src/implementation/StickyToolbar.tsx, uui-editor/src/implementation/Toolbars.tsx
=> [SlateEditor] Fix toolbar focus

uui/components/filters/PresetPanel/PresetActionsDropdown.module.scss, uui/components/filters/PresetPanel/PresetActionsDropdown.tsx
=> [PresetActionsDropdown]: fix splitters, change delete icon

server/api/fileUpload.js, uui-editor/src/SlateEditor.module.scss, uui-editor/src/SlateEditor.tsx, uui-editor/src/implementation/StickyToolbar.tsx, uui-editor/src/migrations/normalizers.ts, uui-editor/src/plugins/attachmentPlugin/AttachFileButton.tsx, uui-editor/src/plugins/imagePlugin/AddImageModal.tsx, uui-editor/src/plugins/imagePlugin/ImageElement.tsx, uui-editor/src/plugins/imagePlugin/imagePlugin.tsx, uui-editor/src/plugins/uploadFilePlugin/file_uploader.ts
- fix initial image and caption width
- attach upload button
- fix focus out for inner scroll example
=> [SlateEditor] Fix initial image and caption width & attach upload button

uui-editor/src/plugins/imagePlugin/ImageElement.tsx
Fixes image width when uploaded
=> [SlateEditor] fix image width when uploaded

uui-e2e-tests/e2e.Dockerfile, uui-e2e-tests/framework/types.ts, uui-e2e-tests/framework/utils/testBuilder.ts, uui-e2e-tests/package.json, uui-e2e-tests/playwright.config.ts, uui-e2e-tests/tests/screenshot.e2e.ts, yarn.lock
=> Increase expect timeout for slow tests

uui-editor/src/plugins/imagePlugin/ImageElement.tsx
=> [SlateEditor] Hack image width

uui-editor/src/migrations/normalizers.ts, uui-editor/src/plugins/imagePlugin/ImageElement.tsx, uui-editor/src/plugins/imagePlugin/imagePlugin.tsx, uui-editor/src/plugins/imagePlugin/types.ts
=> normalize img width

uui-editor/src/SlateEditor.tsx, uui-editor/src/plugins/uploadFilePlugin/constants.ts, uui-editor/src/plugins/uploadFilePlugin/file_uploader.ts, uui-editor/src/plugins/uploadFilePlugin/uploadFilePlugin.ts
Unlink upload plugin from deserialization `insertData` plugin
=> [SlateEditor] Unlink upload plugin from deserialialization

uui-editor/src/plugins/uploadFilePlugin/file_uploader.ts, uui-editor/src/plugins/uploadFilePlugin/uploadFilePlugin.ts
=> [SlateEditor] Fix files upload

uui/components/buttons/LinkButton.tsx, uui/components/widgets/Badge.tsx
=> Convert LinkButtonProps and BadgeProps to make them overridable

app/src/demo/tables/filteredTable/FilteredTable.module.scss, app/src/demo/tables/filteredTable/columns.tsx
=> [Filtered Table]: Align demo pattern with Figma

uui-e2e-tests/scripts/cmd/cmdRunPwDocker.ts
=> Podman on MacOS requires abs path for files outside of root dir

server/utils/cspUtil.js
=> Improve naming of some constants. Add comments.

app/src/App.tsx, app/src/common/AppHeader.tsx, app/src/helpers/appTheme.tsx, uui-components/src/helpers/getHtmlDir.tsx, uui-components/src/helpers/index.ts, uui-components/src/helpers/useDocumentDir.tsx, uui-components/src/layout/ScrollBars.tsx, uui-components/src/overlays/Dropdown.tsx, uui/components/overlays/DropdownMenu.tsx
=> remade useDocumentDir hook

uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyFetchingAdvisor.ts, uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyTree.ts, uui-core/src/data/processing/views/tree/treeStructure/helpers/FetchingHelper.ts
- Fixed reloading data on deps change.
- Fixed loading data on scrolling up with minus count values.
=> [LazyDataSource]: Fixed reload data on deps change and fixed fetching data on scroll up with minus count.

uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyTree.ts, uui-core/src/data/processing/views/tree/treeState/TreeState.ts
Fixed extra loading items, set by setItems of dataSource.
=> [useLazyTree]: Prevent loading items set by setItems via dataSource.

uui-build/ts/tasks/themeTokensGen/main.ts, uui-build/ts/tasks/themeTokensGen/utils/fileUtils.ts
=> Fix error when destination dir does not exist

uui-build/bin/cli.js, uui-build/bin/generateThemeVariables/main.js, uui-build/package.json, uui-build/readme.md, uui-build/ts/tasks/themeTokensGen/main.ts
=> Use bin script to generate mixins. Rename CLI arguments.

uui-components/src/pickers/hooks/usePicker.ts, uui-core/src/types/pickers.ts
Closes: https://github.com/epam/UUI/issues/2395
Added selection to footer props.
=> [Pickers]: Added selection to footer props.

app/src/sandbox/reactQueryLocationsTable/LocationsTable.tsx, app/src/sandbox/reactQueryLocationsTable/useCascadeSelection.ts
=> [ReactTanStackLocationsTable]: fixed cascade selection.

changelog.md, uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLoadData.ts
Fixed requesting extra items on scroll lazy.
=> [LazyDataSource]: Fixed requesting extra items on scroll lazy.

changelog.md, uui-components/src/pickers/hooks/usePickerList.ts, uui/components/pickers/__tests__/PickerList.test.tsx
Fixed updating predefined checked values in PickerList.
=> [PickerList]: predefined value update.

uui-editor/src/plugins/listPlugin/listPlugin.tsx, uui-editor/src/plugins/paragraphPlugin/constants.ts, uui-editor/src/plugins/uploadFilePlugin/uploadFilePlugin.tsx
Improve pasting lists from Word
=> [Editor] Improve list pasting from word

uui/components/fileUpload/FileCard.module.scss, uui/components/fileUpload/FileCard.tsx
=> File upload: Change error icon color to error-70

uui-core/src/data/processing/views/__tests__/LazyListView.show-only-selected.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree.test.ts, uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/__tests__/useLazyTree.test.ts, uui/components/datePickers/CalendarPresets.tsx
Fixed dataSources tests warnings/errors.
=> [DataSources]: Fixed datasources tests warnings/errors.

app/src/demo/tables/editableTable/helpers.ts
Fixed timeline demo subtotal calculations.
=> [EditableTableDemo]: Fixed timeline demo subtotals calculations.

uui/components/pickers/DataPickerFooter.tsx
=> [PickerInput]: fixed to hide footer while searching as in the single mode as in the multi mode.

app/src/docs/_examples/tables/TableWithExpandableRows.example.tsx, app/src/docs/_examples/tables/TableWithExpandableRows.module.scss, app/src/docs/tables/Advanced.doc.tsx, public/docs/content/examples-tables-ColumnFiltersTable.json, public/docs/content/examples-tables-TableWithExpandableRows.json
Issue: https://github.com/epam/UUI/issues/392
In progress...
=> [DataTableWithExpandableRows]: added simple PoC demo.

uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyFetchingAdvisor.ts, uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyTree.ts
Fixed API calls while fast scrolling.
=> [useLazyTree]: fixed api calls while very fast scrolling.

uui-components/src/pickers/KeyboardUtils.tsx, uui/components/pickers/__tests__/PickerInput.test.tsx
Closes https://github.com/epam/UUI/issues/2468
=> [PickerInput]: fixed clear disabled rows via backspace.

uui-components/src/table/DataTableHeaderCell.tsx, uui/components/tables/DataTableHeaderCell.module.scss
Closes https://github.com/epam/UUI/issues/2444
=> [DataTableHeaderCell]: Fixed text selection while click on resize without preventing event from bubbling.

test-utils/src/rendering/setupComponentUtils.tsx, uui/components/pickers/__tests__/PickerInput.test.tsx
Added tests for issue, resolved in https://github.com/epam/UUI/pull/2499
=> [PickerInput]: added tests for value synchronization.

.github/workflows/base.yml, GitVersion.yml
2963
Adding GitVersion configuration file to manage rules for different branches
=> 2963 Adding Gitversion configuration

uui-core/src/data/processing/views/tree/ItemsStorage.ts, uui-core/src/data/processing/views/tree/hooks/strategies/asyncTree/useAsyncTree.ts, uui-core/src/data/processing/views/tree/hooks/strategies/asyncTree/useLoadData.ts, uui-core/src/data/processing/views/tree/treeState/TreeState.ts
Fixed problem with refetching data on deps change, while using useAsyncTree.
=> [useAsyncTree]: fixed problem with refetching data on deps change.

uui/components/pickers/DataPickerRow.tsx, uui/components/pickers/__tests__/__snapshots__/DataPickerBody.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/DataPickerRow.test.tsx.snap, uui/settings.ts, uui/settings.types.ts
Returned defaults for DataPickerRow
=> Returned defaults for DataPickerRow

GitVersion.yml
3238
Fixing incorrect increment strategy for Gitversion
=> 3238 Update increment strategy for prod branch

app/src/demo/tables/masterDetailedTable/MasterDetailedTable.tsx, app/src/demo/tables/masterDetailedTable/filters.ts, server/helpers/getFilterPredicate.js, server/helpers/getOrderComparer.js
* Fix filtering date ranges in demo table
* Fix sorting for dates in demo tables
=> Fix filtering date ranges in demo table

uui/components/tables/columnsConfigurationModal/ColumnRow.module.scss, uui/components/tables/columnsConfigurationModal/ColumnRow.tsx, uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap
[ColumnsConfigurationModal]: fixed vertical paddings
=> [ColumnsConfigurationModal]: fixed vertical paddings

GitVersion.yml
3251
Update gt mode for main branch
=> 3251 Update mode foe main branch

changelog.md, uui-core/src/hooks/useVirtualList/useVirtualList.ts
[VirtualList]: fixed estimatedHeight calculations in components with pagination
=> [VirtualList]: 'estimatedHeight' calculations in components with pagination

.github/workflows/base.yml
3251
Update HELM chart version pattern to avoid any issues with deployment
=> fix/3251 Update helm version pattern

app/.eslintrc.js, app/src/docs/_examples/datePicker/Filter.example.tsx, app/src/docs/_examples/datePicker/Footer.example.tsx, app/src/docs/_examples/rangeDatePicker/PresetsAndFooter.example.tsx, app/src/docs/_examples/tables/ColumnFiltersTable.example.tsx, app/src/docs/_examples/tables/FiltersPanelBasic.example.tsx, app/src/docs/_examples/tables/PresetsPanelBasic.example.tsx, app/src/docs/_examples/tables/useTableState/useTableState.example.tsx, app/src/docs/_examples/tables/useTableState/useTableStateWithIEditable.example.tsx
=> remove dayJsHelper from examples, since it broke codesandbox

app/src/docs/IconButton.doc.tsx
Fixed display of colors in color picker for the IconButton in the property explorer
=> [Site]: PE fixed colors in IconButton color picker

changelog.md, uui-timeline/src/TimelineGrid.tsx, uui-timeline/src/TimelineScale.tsx, uui-timeline/src/draw/scale.ts, uui-timeline/src/draw/types.ts
Added possibility to customise today line height in TimelineScale.
=> [TimelineScale]:  today line height customisation ability.

app/src/demo/tables/filteredTable/FilteredTable.module.scss, app/src/docs/_examples/tables/PresetsPanelBasic.example.tsx, app/src/docs/_examples/tables/useTableState/useTableState.example.tsx, app/src/docs/_examples/tooltip/CustomMarkup.example.tsx, app/src/docs/_examples/tooltip/CustomMarkupExample.module.scss
[Site]: fixed Presets examples layout, fixed custom Tooltip layout
see DataTables examples with Presets, Tooltip custom example
=> [Site]: fixed Presets examples layout, fixed custom Tooltip layout

uui-build/package.json, uui-build/rollup/rollup.config.js, uui/components/typography/Text.tsx, yarn.lock
=> replace rollup-plugin-postcss-modules

changelog.md, uui-build/config/bundleSizeBaseLine.json, uui-components/src/overlays/Dropdown.tsx
=> [DatePicker]: fixed body close in date picker input scrolled out from view

app/src/docs/_examples/multiSwitch/Basic.example.tsx
Added new examples to `MultiSwitch`
#2616
=> [MultiSwitch]: new examples

app/src/docs/_examples/tables/LazyTable.example.tsx, app/src/documents/structureComponents.ts, uui-components/src/table/tableCellsSelection/DataTableSelectionProvider.tsx, uui-components/src/table/tableCellsSelection/__tests__/helpers.test.tsx, uui-components/src/table/tableCellsSelection/__tests__/useSelectionManager.test.tsx, uui-components/src/table/tableCellsSelection/hooks/helpers.ts, uui-components/src/table/tableCellsSelection/hooks/useSelectionManager.tsx, uui-components/src/table/tableCellsSelection/mocks/tables.tsx, uui-components/src/table/tableCellsSelection/types.ts
=> [DataTable]: fixed error while using lazy table with copy cell feature

app/src/data/codesandbox/tsconfig.json, changelog.md, next-demo/next-app/tsconfig.json, next-demo/next-pages/tsconfig.json, templates/uui-nextjs-template/template/tsconfig.json, templates/uui-vite-template/tsconfig.json, tsconfig.json
=> Update TS target

changelog.md, uui-components/src/table/DataTableCellContainer.tsx, uui-core/src/helpers/withMods.ts, uui/components/tables/DataTable.tsx, uui/components/tables/DataTableRow.tsx
=> Fix with mods forward ref for React.memo components

changelog.md, public/docs/content/examples-text-Basic.json, uui-build/config/bundleSizeBaseLine.json, uui/assets/styles/helpers.scss, uui/assets/styles/index.scss, uui/assets/styles/typography.scss, uui/components/fileUpload/__tests__/__snapshots__/DropSpot.test.tsx.snap, uui/components/fileUpload/__tests__/__snapshots__/FileCard.test.tsx.snap, uui/components/filters/__tests__/__snapshots__/filtersPanel.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, uui/components/tables/__tests__/__snapshots__/DataTableHeaderCell.test.tsx.snap, uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, uui/components/typography/Text.tsx, uui/components/typography/__tests__/__snapshots__/Text.test.tsx.snap
=> [Text]: use .uui-typography-inline instead of .uui-typography class 

app/src/data/settings_4px.ts, changelog.md, uui-components/src/inputs/DatePicker/Calendar.tsx, uui/components/datePickers/Calendar.module.scss, uui/components/datePickers/Calendar.tsx, uui/components/datePickers/CalendarPresets.tsx, uui/components/datePickers/DatePicker.tsx, uui/components/datePickers/DatePickerBody.module.scss, uui/components/datePickers/DatePickerBody.tsx, uui/components/datePickers/RangeDatePickerBody.module.scss, uui/components/datePickers/__tests__/__snapshots__/Calendar.test.tsx.snap, uui/components/datePickers/__tests__/__snapshots__/DatePickerBody.test.tsx.snap, uui/components/datePickers/__tests__/__snapshots__/RangeDatePickerBody.test.tsx.snap, uui/components/overlays/Modals.tsx, uui/components/overlays/__tests__/Modals.test.tsx, uui/components/overlays/__tests__/__snapshots__/ConfirmationModal.test.tsx.snap, uui/components/overlays/__tests__/__snapshots__/Modals.test.tsx.snap, uui/components/pickers/PickerModal.tsx, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap, uui/settings.ts
* [ModalFooter], [ModalHeader]: removed FlexRow props, removed unused 'Modal' settings
* [DatePicker]: improved size customization
=> Size theming improvement

app/src/docs/Dropdown.doc.tsx, epam-assets/theme/variables/fresh_4px.scss, epam-assets/theme/variables/loveship.scss, epam-assets/theme/variables/loveship_dark.scss, epam-assets/theme/variables/promo.scss, epam-promo/components/layout/FlexItems/FlexRow.tsx, loveship/components/layout/FlexItems/FlexRow.tsx, public/docs/content/dropdown-descriptions.json, public/docs/content/examples-dropdown-VirtualElementCanvas.json, public/docs/content/examples-dropdown-VirtualElementOnMouseCoordinates.json, uui-components/src/inputs/Slider/SliderHandle.tsx, uui/components/layout/FlexItems/FlexRow.module.scss, uui/components/overlays/DropdownMenu.tsx
=> Fixed comments - issue #2663

app/src/helpers/appTheme.tsx
[Site]: Fixed applying overrides to the application when changing the theme
=> [Site]: Fixed applying overrides

uui-components/src/inputs/TextInput.module.scss, uui-components/src/pickers/KeyboardUtils.tsx, uui-components/src/pickers/PickerToggler.module.scss, uui-components/src/pickers/PickerToggler.tsx, uui/components/pickers/DataPickerBody.tsx, uui/components/pickers/__tests__/PickerInput.test.tsx, uui/components/pickers/__tests__/__snapshots__/DataPickerBody.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap, uui/components/pickers/__tests__/__snapshots__/PickerToggler.test.tsx.snap
=> [PickerInput]: fixed focused item selected after 'Enter' key on Clear button

server/api/docsGen.js
=> Mcp improvements

changelog.md, uui-components/src/inputs/Rating/BaseRating.tsx, uui-components/src/inputs/Rating/Rating.module.scss, uui-components/src/inputs/Rating/Rating.tsx, uui/components/inputs/__tests__/__snapshots__/Rating.test.tsx.snap
[Rating]: fixed wrong rating calculations in 'block' container, 'sticky' value on hover
#2813
=> [Rating]: fixed multiple visual and interaction issues

uui-e2e-tests/tests/previewTests/preview.e2e.ts
[E2E]: excluded unstable tests
=> [E2E]: excluded unstable tests

uui/components/typography/Text.tsx
=> [Text]: fixed assigning styles to an immutable object

app/src/docs/_examples/tables/ArrayTable.example.tsx, uui-core/src/data/processing/views/dataRows/stats.ts, uui-core/src/data/processing/views/dataRows/useBuildRows.ts, uui-core/src/data/processing/views/dataRows/useSelectAll.ts
=> [DataSources]: Added correct handling of selectAll for views with disabled checkboxes.

app/src/common/docs/DocsSidebar.tsx, changelog.md, uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts, uui-core/src/data/processing/views/__tests__/AsyncListView.test.ts, uui-core/src/data/processing/views/__tests__/LazyListView.tree.test.ts, uui-core/src/data/processing/views/dataRows/useDataRowProps.ts
[PickerInput]: fix incorrect selection state in modal for single selection mode
#2846
=> [PickerInput]: fix incorrect selection state in modal

app/src/docs/_examples/dropdown/CloseFromBody.example.tsx, app/src/docs/_examples/dropdown/CloseOpenModifiers.example.tsx, app/src/docs/_examples/dropdown/HandleStateByYourself.example.tsx, app/src/docs/_examples/dropdownMenu/Basic.example.tsx
=> [Dropdown]: Increase padding to 6px between dropdown and button

uui-editor/src/SlateEditor.module.scss
[RTE]: removed horizontal scroll in empty state
=> [RTE]: removed horizontal scroll in empty state
