epam/UUI

.vscode/settings.json

Added settings to enable automatic checking of `stylelint` rules and fix them if possible when saving for VSCode.

settings: enable stylelint and auto fix on save for vscode

---

epam-promo/components/inputs/__tests__/__snapshots__/Checkbox.test.tsx.snap
epam-promo/components/inputs/__tests__/__snapshots__/RadioInput.test.tsx.snap
epam-promo/components/layout/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
epam-promo/components/layout/__tests__/__snapshots__/RadioGroup.test.tsx.snap
epam-promo/components/pickers/DataPickerRow.tsx
epam-promo/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap
loveship/components/inputs/__tests__/__snapshots__/Checkbox.test.tsx.snap
loveship/components/inputs/__tests__/__snapshots__/RadioInput.test.tsx.snap
loveship/components/layout/__tests__/__snapshots__/CheckboxGroup.test.tsx.snap
loveship/components/layout/__tests__/__snapshots__/RadioGroup.test.tsx.snap
loveship/components/pickers/__tests__/__snapshots__/PickerListItem.test.tsx.snap
loveship/components/tables/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap
loveship/components/tables/__tests__/__snapshots__/DataTableHeaderRow.test.tsx.snap
uui-components/src/inputs/Checkbox.tsx
uui-components/src/inputs/RadioInput.tsx
uui-components/src/inputs/Switch.tsx

When table row is clicked, the checkbox whose top-level element is ```<label></label>``` triggers propagation by default. This behavior is fixed on pickerinput and tables.

[Bugfix]: Fix table row, picker row double click on checkbox label

---

changelog.md
uui-components/src/layout/VirtualList.scss

renderRow the contents of the '.container3' do not go beyond the dropdown.

[VirtualList]: fix the width for the '.wrapper' so that when using

---

changelog.md
loveship/components/inputs/SliderRating.scss
loveship/components/inputs/SliderRating.tsx

fix #476 (https://git.epam.com/epm-tmc/ui/-/issues/476)

[SliderRating]: fix too many rendered tooltips so that rendering of the SliderRation does not hangs

---

app/src/docs/assets/Icons.doc.tsx

Added spaces around unfound icon's name

---

app/package.json
app/src/analyticsEvents/listeners/AmplitudeListener.ts
app/src/data/codesandbox/package.json
app/src/docs/examples/contexts/AnalyticsContextBase.example.tsx
edu-core-routing/urlParser.ts
loveship/components/datePickers/docs/rangeDatePicker.doc.tsx
next-app/tsconfig.json
package.json
templates/uui-cra-template/template.json
tsconfig.json
uui-build/package.json
uui/helpers/urlParser.ts
yarn.lock

1. Upgrade ```Typescript```
2. Upgrade ```Amplitude-JS```
3. Remove `importHelpers` flag from tsconfig.json, which required peer dep ```tslib``` to be installed

[Typescript, Amplitude]: Upgrade and remove importing helpers

---

uui/data/forms/Form.tsx
uui/data/forms/useForm.ts

Issue: #258
**Problem:** 
When we write a redirect logic in our onSuccess function, it will be called on both two cases.
1. On direct click to form save button.
2. On click to save button from beforeLeave modal.
When saving form from beforeLeave modal it causes to add unnecessary route to browser history.
**Solution:** 
Inside our onSuccess hook we need to know if form successfully saved from beforeLeave modal or from form submit button.
To do that, I've added `isSavedBeforeLeave` argument to onSuccess function.

[Form]: Add isSavedBeforeLeave arg to onSuccess hook

---

app/src/docs/examples/virtualList/Advanced.example.tsx
epam-promo/components/tables/DataTableHeaderRow.tsx
loveship/components/tables/DataTableHeaderRow.tsx
loveship/components/tables/__tests__/__snapshots__/DataTable.test.tsx.snap
loveship/components/tables/__tests__/__snapshots__/DataTableHeaderRow.test.tsx.snap
uui-components/src/table/DataTableRowContainer.tsx
uui/hooks/useVirtualList.ts

1. Add flexBasis calculation back to fixed cells wrapper on DataTable.
2. Intentionally remove ```key``` prop from DataTableHeaderCell to allow multiple DnD and resizing action.
3. Remove redundant check on useVirtualList to fix AdvancedVirtualList example.

[VirtualList, DataTableHeaderCell]: Fix header cell DnD; Fixed cells wrapper flexBasis

---

app/src/common/AppFooter.tsx
app/src/common/sidebar/SidebarButton.tsx
app/src/common/slider/Slider.tsx
app/src/demo/DemoPage.tsx
app/src/docs/examples/scrollSpy/BasicScrollSpy.example.tsx
app/src/landing/ContactsBlock.tsx
app/src/landing/HeroBlock.tsx
app/src/landing/ProjectsBlock.tsx
app/src/landing/StartedBlock.tsx
app/src/landing/TechnologiesBlock.tsx
app/src/sandbox/forms/ExperienceEditor.tsx
app/src/sandbox/forms/PersonDetailEditor.tsx
app/src/sandbox/scroll-spy/ScrollSpyAnchor.tsx
app/src/sandbox/scroll-spy/ScrollSpyModal.tsx
changelog.md
epam-promo/components/widgets/Paginator.tsx
loveship/components/widgets/Paginator.tsx
uui-components/src/inputs/Slider/RangeSlider.tsx
uui-components/src/inputs/Slider/Slider.tsx
uui-components/src/overlays/ModalWindow.tsx
uui-components/src/table/DataTableHeaderRow.tsx
uui-components/src/table/DataTableRowContainer.tsx
uui-core/types/props.ts
yarn.lock

As per Typescript docs changelog, since 4.5.0, we can now create types using template string type
[4.5.0 Changelog]https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html
So, I added an additional check to check data-* attributes passed to rawProps
Compiler will allow anything matching the template: `data-${string}` and will complain in cases like `data232324-` since it's not matching the string type template.

[RawProps]: Detalize data-attributes via template string types

---

epam-promo/components/buttons/Button.scss

[Button]: issue #517 - fixed text color for "fill:light" props in Promo skin

[Button]: fixed text color for "fill:light" props in Promo skin

---

uui-editor/src/plugins/listPlugin/listPlugin.tsx

bug related with #259 
Now, I can select element with list, transform that to new list, without crashing
Before chnging work like that:

[RTE] Change connection of ListPlugin in RTE

---

app/src/data/codesandbox/service.ts
app/src/docs/examples/blocker/Advanced.example.tsx
app/src/docs/examples/blocker/Basic.example.tsx
loveship/docs/contexts/RelativePanelContext.tsx
next-app/components/lib/LoaderExample.tsx
public/docs/content/examples-blocker-Basic.json

Fixes #826 
DatePicker `value` accepts YYYY-MM-DD format, so changed example values to that.
Also removed unnecessary console.log introduced in other bugfix.

Fix wrongly formatted DatePicker value #826

---

uui-components/src/overlays/Snackbar.tsx

Changed reference binding. Since when rendering multiple components, you need a separate corresponding reference for each notification. In the previous version, there was a single reference to the element to which all notices were attached. As a result, changes to the assignments of the CSSTransition classes that control the entry/exit animation of the notification components failed.

[Snackbar]: show several notification in row

---

loveship/components/layout/docs/controlGroup.doc.tsx

- added onClick handlers to Buttons, otherwise the tabIndex will be set with the value -1

[Docs]: refactor ControlGroup loveship explorer

---

epam-promo/components/navigation/MainMenu/__tests__/__snapshots__/MainMenuAvatar.test.tsx.snap
epam-promo/components/widgets/__tests__/Avatar.test.tsx
epam-promo/components/widgets/__tests__/__snapshots__/Avatar.test.tsx.snap
epam-promo/components/widgets/__tests__/__snapshots__/AvatarStack.test.tsx.snap
epam-promo/package.json
loveship/components/navigation/MainMenu/__tests__/__snapshots__/MainMenuAvatar.test.tsx.snap
loveship/components/widgets/__tests__/__snapshots__/Avatar.test.tsx.snap
loveship/components/widgets/__tests__/__snapshots__/AvatarRow.test.tsx.snap
loveship/components/widgets/__tests__/__snapshots__/AvatarStack.test.tsx.snap
uui-components/src/widgets/Avatar.test.tsx
uui-components/src/widgets/Avatar.tsx

For what: improve Avatar component, add handling of errors. 
Current behaviour: if there is incorrect path in Avatar (not undefined) -> Avatar shows broken image, not stub. 
After improvement: if there is incorrect path in Avatar -> Avatar shows stub. 
In case when developer pass rawProps with his own handler for onError -> we don't show stub, handling of error on developer side.

[Avatar]: handle error on loading image and shows stub

---

changelog.md
uui-components/src/pickers/PickerInputBase.tsx

- fix update `dataSourceState` when programmatically selected and already loaded value in Show selected mode if API returns empty array

[PickerInput]: fix update dataSourceState.

---

changelog.md
uui-components/src/inputs/NumericInput.tsx
uui-core/src/helpers/__tests__/numericInputCalculations.test.tsx
uui-core/src/helpers/numericInputCalculations.ts

Closes: https://github.com/epam/UUI/issues/916
Replaced `toFixed` with a function, which is not rounding up the number.
https://user-images.githubusercontent.com/22456368/211508939-d26703f8-ce58-4318-8459-4b7e48cd3ec9.mov
https://user-images.githubusercontent.com/22456368/211508773-935e5848-5ad2-4eef-bec4-dbf9e0b1d8dc.mov

[NumericInput]: fixed formatOptions prop works incorrect 

---

epam-promo/components/tables/columnsConfigurationModal/ColumnsConfigurationModal.tsx
loveship/components/tables/columnsConfigurationModal/ColumnsConfigurationModal.tsx

Changed the tooltip to the position, which is corresponding to the design, placed at the issue: https://github.com/epam/UUI/issues/878

[ColumnsConfigurationModal]: tooltip position fixed when no columns selected.

---

app/src/docs/_examples/numericInput/Formatting.example.tsx
changelog.md
uui-components/src/inputs/NumericInput.tsx

Closes #1010
This PR adds support of custom formatting in readonly mode for `NumericInput`.
https://user-images.githubusercontent.com/39378793/222702897-0f420941-2773-4d59-981b-dc868728739c.mp4

[NumericInput] Add custom formatting 

---

app/src/common/docs/ComponentEditor.tsx

Fixes #1088
Now `NumericInput` property explorer should chnage the value while typing in it.

[ComponentEditor] Fix `NumericInput` Property Explorer 

---

uui-editor/src/SlateEditor.tsx
uui-editor/src/plate/plugins/Toolbars.tsx

This PR hides toolbar when editor not in focus.
**Before:**
**After:**

[SlateEditor] Hide toolbar when editor not in focus

---

uui-editor/src/implementation/Toolbar.tsx
uui-editor/src/plate/plugins/tablePlugin/Table.scss
uui-editor/src/plate/plugins/tablePlugin/tablePlugin.tsx

Fix table in SlateEditor:
- Adds header row on creation
- Now first cell selected after creation
- Preserves initial table width
- Now resizing works  
- Hides `remove table` button from plate lib
- Now horizontal scroll displayed only when needed (on squeezing browser window)

[SlateEditor] Fix table creation

---

uui-editor/src/SlateEditor.tsx

This PR skips state updates when editor in readonly mode.

[SlateEditor] Skip state updates when in readonly

---

uui-components/src/overlays/Dropdown.tsx

Without the change, the value `0` is ignored, which prevents dropdowns/tooltips from closing immediately.
Closes #1113.

[Dropdown] Change `||` to `??` when choosing `closeDelay` value with `closeOnMouseLeave` set to `boundary`

---

uui-core/src/types/components/filterItemBody.ts
uui/components/filters/FilterPickerBody.tsx
uui/components/filters/FiltersPanelItem.scss
uui/components/filters/FiltersPanelItem.tsx
uui/components/pickers/PickerInput.tsx

Info ℹ️ 
https://github.com/epam/UUI/issues/1019
Dropdown is not closing after clicking close button or `done` - on mobile view.
Added `popperModifiers` to Filter Panel

[FilterPanel]: No possibility to close the filter modal window by clicking on the cross icon (mobile) #1019

---

app/src/demo/form/DemoForm.tsx
app/src/demo/form/validationShema.ts

Fixed an issue with the education graduation year in the form demo.
The second case was resolved by not restricting a user from entering value < 1950 and providing validation
Related to:
https://github.com/epam/UUI/issues/1132

[1132] - Fixed form demo date picker issues

---

app/src/data/codesandbox/index.tsx
uui-core/src/data/forms/__tests__/shouldCreateUndoCheckpoint.test.tsx
uui-core/src/data/forms/shouldCreateUndoCheckpoint.ts
uui-core/src/data/forms/useForm.ts

Undo checkpoints are created intelligently now. 
Instead of creating them on each change (i.e. character typed in an input field), we create them only on significant changes.

useForm - smarter undo checkpoints

---

uui-components/src/navigation/ScrollSpy.tsx

Fixed a bug with ScrollSpy hook.
Root cause:
The bug appears if a new spied element appears on the screen before the last active one left it. Then if the last active lefts the screen hook sets the active element to '' even though a new element is on the screen.
Related to:
https://github.com/epam/UUI/issues/1001
Note for testers (will be copied to the issue):
Test it with the most possible variations of space between, before, and after the spied elements (different amounts of spied elements too)

Bugfix/use scroll spy fix #1001

---

uui-core/src/data/processing/views/tree/EditableTree.ts

Fixes performance issue of `Tree.patch` method.
https://user-images.githubusercontent.com/22456368/230401293-a2ac41e6-2f63-4157-b804-f1d173b893df.mov
https://user-images.githubusercontent.com/22456368/230401844-c9692b5e-d6f3-4c10-94a6-6a799458fa2b.mov

[Tree] Patch performance improvement.

---

uui/components/pickers/DataPickerHeader.tsx

Fixed a crash if you provide non-string to DataPickerHeader as title
Related to:
https://github.com/epam/UUI/issues/1182

Bugfix/epam/column filter fix #1182

---

changelog.md
uui-components/src/overlays/Tooltip.tsx
uui-core/src/types/components/Tooltip.ts

https://github.com/epam/UUI/issues/1192
[1192] - added rawprops to the Tooltip

[1192] - added rawprops to the Tooltip

---

app/src/docs/_examples/richTextEditor/Basic.example.tsx
app/src/docs/_examples/richTextEditor/WithInnerScroll.example.tsx
next-app/pages/editor.tsx
uui-editor/src/SlateEditor.tsx

Disables auto focus to prevent jumps to the last editor when open page with multiple editor windows.

[SlateEditor] Disable auto focus

---

uui-core/src/data/processing/views/BaseListView.tsx

Added safe code for `getEstimatedChildrenCount` if no item is present in the tree.

[Datasource]: fixed estimated children count.

---

app/src/docs/_props/epam-promo/components/datePickers/rangeDatePicker.props.tsx
app/src/docs/_props/loveship/components/datePickers/rangeDatePicker.props.tsx
changelog.md
uui-components/src/inputs/DatePicker/BaseRangeDatePicker.tsx
uui-core/src/types/components/datePicker/BaseRangeDatePicker.ts
uui/components/datePickers/__tests__/RangeDatePicker.test.tsx

https://github.com/epam/UUI/issues/1244
Added new prop "onOpenChange" to RangeDatePicker that calls a callback with current open state

Feature/add new prop rangedatepicker #1244

---

app/src/docs/_props/epam-promo/components/datePickers/rangeDatePicker.props.tsx
app/src/docs/_props/loveship/components/datePickers/rangeDatePicker.props.tsx
uui/components/filters/FiltersPanelItem.scss

- Fixed height for filter panel and filter panel footer: 
| How it was  | Should be |
| ------------- | ------------- |
| <img width="428" alt="Screenshot at Apr 26 21-50-29" src="https://user-images.githubusercontent.com/26334961/234674316-4f4bd7b5-6e9d-482f-ac98-52149e92e8df.png"> | <img width="289" alt="Screenshot at Apr 26 21-41-06" src="https://user-images.githubusercontent.com/26334961/234674460-6353ae27-2461-4ad4-9f4c-a9f3625af2d5.png"> |
| <img width="441" alt="Screenshot at Apr 26 21-52-44" src="https://user-images.githubusercontent.com/26334961/234674715-09e0d01e-411f-47d8-a99f-c201a81d92d0.png">| <img width="299" alt="Screenshot at Apr 26 21-41-37" src="https://user-images.githubusercontent.com/26334961/234674788-41fce5d2-22ff-423a-a544-ed7df31b4583.png">|
- Small fix for space …

[FilterPanel]: fixed height for mobile panel

---

uui-editor/src/plate/plugins/notePlugin/notePlugin.tsx

Fixes notes `Enter` key events behaviour.

[SlateEditor] Make notes `Enter` key events behave like lists

---

uui-core/src/data/processing/views/BaseListView.tsx

Added fix of missing parent ids of partially checked items, which are nested 2+ levels.

[LazyListView]: add fix of missing nested ids of lazy ds partially checked parents.

---

uui/components/filters/PresetPanel/PresetInput.module.scss

https://github.com/epam/UUI/issues/1402
Issue related to when we're changing the size of the elements in the ResizeObserver callback. In this case, the observer is called again and again, leading to an infinite loop. An then when're trying add some preset we're getting this error each time:

[PresetsPanel]: input is not available for "Add Preset" action on mobile devices

---

changelog.md
uui-components/src/inputs/TimePickerBody.tsx

[TimePickerBody]: fixed the bug where `minutes` values that are not a multiple of `minutesStep`, are not rounded up to the nearest multiple of `minutesStep`

TimePickerBody minutesStep bugfix

---

uui-components/src/overlays/Dropdown.tsx

Some properties (like `isInteractedOutside`), that are passed to `renderTarget` function, are created anew on each render, breaking user memoized components.
This pull request move the properties' getters to separate component's methods:
* `isInteractedOutside` (method `getIsInteractedOutside`)
* `onClick` (method `getTargetClickHandler`). Actually, the current version is safe enough, but I decided to move picking the handler to a separate method to make the code a bit cleaner
Additionally, I removed unnecessary condition part `!openOnClick` inside `getTargetClickHandler`, because it is always `true`:
```diff
if (
openOnClick
+ || !openOnHover
- || (
-   !openOnClick
-   && !openOnHover
- )
) {
return this.handleTargetClick;
}
return undefined;
```
There is also `ref` property, but I left …

[Dropdown] Fix `renderTarget` props memoization

---

app/src/common/sidebar/Sidebar.tsx

https://github.com/epam/UUI/issues/1400
We have differences between names of items and that's why we have incorrect value for `!row.isFolded`.
Should be:

bugfix: fixed collapsing components and assets inside sidebar

---

app/src/docs/_props/epam-promo/components/inputs/rating.props.ts

https://github.com/epam/UUI/issues/1411
Include 0 value in Property Explorer for Rating component.

add-0-value-in-property-explorer-rating

---

.github/workflows/trackBundleSizeCommentPR.yml

The comment workflow should run even if prev workflow failed.

---

app/src/docs/_props/epam-promo/components/overlays/alert.props.tsx
app/src/docs/_props/epam-promo/components/overlays/notificationCard.props.tsx
app/src/docs/_props/loveship/components/overlays/alert.props.tsx
app/src/docs/_props/loveship/components/overlays/notificationCard.props.tsx
app/src/docs/_props/uui/components/overlays/notificationCard.props.tsx

[#1551](https://github.com/epam/UUI/issues/1551)
Added `alert` call in with `onClose` callbacks for `NotificationCard` and `Alert` components docs

[Fix] add alert call in `Alert` and `NotificationCard` component docs

---

app/src/docs/_props/epam-promo/docs/editors/IconPicker.tsx

#1550 
Added workaround to handle 'undefined' value for id parameter in `onValueChange` callback

[Fix] Handle 'undefined' value in `onValueChange` cb

---

changelog.md
uui-components/src/pickers/PickerInputBase.tsx
uui-components/src/pickers/PickerToggler.tsx

Fix the issue: Single selection Picker doesn't open by click.
Additionally a fix was applied when `editMode=modal` , a `searchPosition` cannot be `input`.

[Fix] Picker Input single selection toggler opened

---

app/src/common/docs/DocExample.module.scss

Fix on focus style for link icon on Documentation page.
Before:
After:

[Fix] Icon style for Docs header link

---

uui/components/buttons/Button/Button.module.scss

Remove hover color style for focus state for `Button` component.
Before:
After:

[Fix] Button - fix focus styles

---

app/src/docs/VirtualList.doc.tsx
app/src/docs/_examples/dataSources/DataSourceStateIndexToScroll.example.tsx
app/src/docs/_examples/dataSources/DataSourceViewer.code.example.tsx
app/src/docs/_examples/virtualList/Advanced.example.tsx
app/src/docs/_examples/virtualList/ScrollTo.example.tsx
public/docs/content/dataSources-dataSource-state.json
public/docs/content/examples-virtualList-Advanced.json
public/docs/content/examples-virtualList-ScrollTo.json
uui-components/src/layout/VirtualList.tsx
uui-core/src/hooks/useVirtualList/types.ts
uui-core/src/hooks/useVirtualList/useVirtualList.ts
uui-docs/src/dataSources/DataSourceViewer.tsx
uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap

- FIxed bug, related to infinity loop while scrolling to the index, higher that rowsCount (ArrayListView).
- FIxed examples of dataSources and virtualList docs.
- Added example of scrollTo to VirtualList docs.
- Added example to scrollTo to DataSourceState docs.

[VirtualList]: fixed scroll to more than rows count index.

---

uui/components/overlays/Modals.module.scss

https://github.com/epam/UUI/issues/1136 
To avoid overlapping we used dynamic viewport, the size depending on whether the address bar is visible
|   |  |
| ------------- | ------------- |
| <img width="1071" alt="Screenshot 2023-08-31 at 19 06 17" src="https://github.com/epam/UUI/assets/26334961/002249bd-8363-4360-9612-e43bcdad0af0"> | <img width="948" alt="Screenshot 2023-08-31 at 19 11 18" src="https://github.com/epam/UUI/assets/26334961/8427e4a0-66d2-43a7-911d-3ec95ab77c7f"> |
| <img width="716" alt="Screenshot 2023-08-31 at 19 15 02" src="https://github.com/epam/UUI/assets/26334961/2ed671b8-1e08-4c2f-b31f-db66567032be">  | <img width="864" alt="Screenshot 2023-08-31 at 19 26 38" src="https://github.com/epam/UUI/assets/26334961/bf501076-8ed3-4c07-8262-5a51cc5b8df9">  |

[Modals]: controls are not visible if the modal window does not fit on the screen

---

app/src/docs/_examples/dataSources/DataSourceViewer.code.example.tsx
uui-components/src/layout/VirtualList.tsx
uui-core/src/hooks/__tests__/useVirtualList/utils.test.ts
uui-core/src/hooks/useVirtualList/types.ts
uui-core/src/hooks/useVirtualList/useVirtualList.ts
uui-core/src/hooks/useVirtualList/utils.ts
uui-docs/src/dataSources/DataSourceViewer.tsx
uui/components/pickers/DataPickerBody.tsx
uui/components/tables/DataTable.tsx

Changed default rows selector to children of `listContainer` to prevent breaking of consumer's components.

[VirtualList]: changed default rows selector to children of listContainer

---

uui-components/src/pickers/PickerToggler.tsx
uui/components/pickers/PickerItem.module.scss
uui/components/pickers/__tests__/PickerInput.test.tsx
uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap

https://github.com/epam/UUI/issues/1593 
https://github.com/epam/UUI/issues/1589
- Removed the dropdown icon if `minCharsToSearch` props exist. 
- Removed padding 0 from text picker input.

[PickerInput]: Unexpected 'v' icon is displayed and  Incorrect top and bottom padding in drop-down list with two lines text 

---

uui/components/pickers/PickerItem.module.scss
uui/components/pickers/PickerItem.tsx

Issue with padding for `multiline` picker inputs.

[PickerInput]: fix paddings for multiline pickers

---

templates/uui-cra-template/template.json
templates/uui-vite-template/package.json

The issue started to reproduce after @types/react v 18.2.22 was released. Two different versions of @types/react become added to the node_modules: latest version and the version we specified in package.json of our template. When I forced to use only latest version it still showed TS errors upon build. So I forced a previous (18.2.21) version instead.

Fix template apps

---

changelog.md

Added information about `Blocker` and `backgrounReload` prop to the changelog.

[Changelog]: added `backgroundReload` and `Blocker` in `DataTable`/`Pickers` description.

---

uui-components/src/pickers/KeyboardUtils.tsx
uui-components/src/pickers/hooks/usePickerInput.ts
uui/components/pickers/PickerInput.tsx

Enabled removing tags on backspace only if searchPosition = 'input' and editMode != 'modal'.

[PickerInput]: fixed removing tags on pressing backspace.

---

uui-components/src/table/DataTableRow.tsx

#1628
Adds ability to add `rowProps`for `DataTableRow`.

[DataTableRow] Fix data table row `rowProps`

---

app/src/common/AppHeader.tsx
app/src/common/docs/BaseDocsBlock.module.scss
app/src/common/docs/BaseDocsBlock.tsx
app/src/docs/_props/epam-promo/components/typography/richTextView.props.tsx
app/src/docs/_props/loveship/components/typography/richTextView.props.tsx
app/src/docs/_props/uui/components/typography/richTextView.props.tsx
app/src/sandbox/tableColConfigModal/TableColumnConfigModalTest.tsx

…calendar icon from PE examples, [TableColumnConfigModalTest]: changed Badge into StatusIndicator, [AppHeader]: set UUI theme in PE as default

fixPack-Nov16 & portal theme class

---

app/src/common/AppHeader.tsx
app/src/common/docs/BaseDocsBlock.tsx
app/src/common/docs/componentEditor/ComponentEditor.tsx
app/src/common/docs/componentEditor/utils.ts
app/src/documents/DocumentsPage.tsx
app/src/helpers/getCurrentTheme.ts
app/src/helpers/index.ts
app/src/helpers/useTheme.tsx

[Site]: updated query string for theme, removed prefix 'uui-theme'

Updated query string 'theme'

---

uui-components/src/table/columnsConfigurationModal/__tests__/columnsConfigurationUtils.test.tsx
uui-components/src/table/columnsConfigurationModal/__tests__/useConlumnsConfiguration.test.tsx
uui-components/src/table/columnsConfigurationModal/hooks/useColumnsConfiguration.ts

Add test for useColumnsConfiguration hook

[useColumnsConfiguration] Add test for hook

---

uui-core/src/data/processing/views/BaseListView.tsx
uui-core/src/data/processing/views/LazyListView.ts

Placeholders appeared on the first page change, because at that moment there was no checked property in dataSource state.
Also, placeholders appeared on every change of rowOptions (not memorized callbacks).

[DataSources]: Fixed background reload in paged table and filtered table.

---

uui-core/src/data/processing/views/ArrayListView.ts

Fixed explicit cascade selection with search while using ArrayListView/AsyncListView.
https://github.com/epam/UUI/assets/22456368/f38ee18e-2a91-4f09-9de5-138cf336e86a

[ArrayListView]: Fixed cascade selection with search.

---

changelog.md
uui-components/src/overlays/DropdownHelpers.ts
uui/components/inputs/TextInput.tsx

…composedPath(), rather than go through dom tree to detect if click was triggered on node inside parent stop nodes. It was an issues, that dom was updated earlier than event bubble to the parent node.
**Testing notes:**
Need to retest:
- dropdown close on click outside logic
- Dropdown shouldn't close by clicks inside its body
- retest #1045 issue, since prior fix was reverted in flavor of this more versatile fix

[Dropdown]: rework isInteractedOutsideDropdown helper to work with e.composedPath()

---

uui-core/src/data/processing/views/tree/EditableTree.ts

Fixed `cascadeSelection` on clear selected items in `Picker`.

[Tree]: cascadeSelection fixed

---

uui-core/src/services/ApiContext.ts
uui-core/src/services/__tests__/ApiContexts.test.ts
uui-core/src/types/contexts.ts

This PR allows handling non-JSON responses with ApiContext.
To support this, ApiCallOptions is extended as following:
```typescript
export interface ApiCallOptions {
...
/**
* By default, all responses are parsed as JSON.
* This option allows to extract response data in non-json formats.
* The callback is passed with response object, and should return a promise to result to return from the processRequest call.
* Examples:
* (res) => res.text() // parse all responses as text
* (res) => res.status === 200 ? res.json() : res.text() // parse OK response as json, and errors as text
* (res) => res.blob() // get response as Blob object
*/
parseResponse?: (response: Response) => Promise<any>;
}
```

API Context - add options.parseResponse to handle non-JSON formats

---

app/src/docs/_examples/pickerInput/LazyTreeInput.example.tsx
changelog.md
uui-components/src/pickers/bindingHelpers.ts
uui-components/src/pickers/hooks/usePicker.ts
uui-core/src/data/processing/views/ArrayListView.ts
uui-core/src/data/processing/views/BaseListView.tsx
uui-core/src/data/processing/views/LazyListView.ts
uui-core/src/data/processing/views/tree/LoadableTree.ts

- Fixed returning `checked = []` if `emptyValue` is not passed to `PickerInput`.
- Fixed partially selected with predefined selected value.
- Fixed fetching missing parents for selected element in `PickerInput`.

[PickerInput]: fixed loading of selectedId with parents.

---

app/src/common/AppHeader.module.scss
app/src/common/AppHeader.tsx
app/src/docs/_examples/adaptivePanel/Basic.example.tsx
app/src/sandbox/adaptivePanel/AdaptivePanelDemo.tsx
changelog.md
uui-components/src/navigation/MainMenu/MainMenu.tsx
uui-components/src/pickers/PickerToggler.tsx
uui/components/pickers/__tests__/__snapshots__/PickerInput.test.tsx.snap

Bugfix/PickerInput focus locked #1989

---

changelog.md
public/docs/docsGenOutput/docsGenOutput.json
uui/components/inputs/__tests__/TimePicker.test.tsx
uui/components/inputs/__tests__/__snapshots__/TimePicker.test.tsx.snap
uui/components/inputs/timePicker/TimePicker.tsx

Bugfix/TimePicker added property to hide cross #2040

---

uui-components/src/inputs/TextArea.module.scss
uui/components/inputs/TextArea.module.scss

[TextArea]: fixed scroll in disabled and readonly states.

---

changelog.md
uui-components/src/pickers/PickerToggler.tsx

Fixed focus/blur of PickerToggler with searchPosition="none" in editable tables.

[PickerToggler]: Fixed PickerToggler focus/blur while using searchPosition="none"

---

changelog.md
uui-components/src/table/DataTableHeaderCell.tsx
uui/components/tables/DataTableHeaderCell.tsx

[DataTableHeaderCell]: stopped other onClick events during resizing

---

uui-core/src/data/processing/views/__tests__/ArrayListView.patch-items.test.ts
uui-core/src/data/processing/views/__tests__/AsyncListView.patch-items.test.ts
uui-core/src/data/processing/views/__tests__/LazyListView.patch-items.test.ts
uui-core/src/data/processing/views/tree/hooks/strategies/asyncTree/useAsyncTree.ts
uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyTree.ts
uui-core/src/data/processing/views/tree/hooks/strategies/syncTree/useSyncTree.ts

Fixed missing `fixItemBetweenSortings`.

[useTree]: fixed missing `fixItemBetweenSortings`.

---

uui-core/src/data/processing/views/__tests__/LazyListView.search.test.ts
uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyTree.ts
uui-core/src/data/processing/views/tree/hooks/strategies/types/common.ts
uui-core/src/data/processing/views/tree/hooks/types.ts
uui-core/src/types/dataSources.ts

Fixed `flattenSearchResults` subtitle.

[LazyDataSource]: Fixed returning `flattenSearchResults` option in `view.getConfig`.

---

app/src/docs/_examples/pickerInput/LazyTreeInput.example.tsx
uui-core/src/data/processing/views/tree/treeStructure/helpers/CheckingHelper.ts

Fixed clearing explicitly checked children after search clear and checking parent in implicit mode.
https://github.com/epam/UUI/assets/22456368/8a03c81c-2369-4b99-8a81-1269695494ac

[LazyDataSource]: fix clearing of explicitly checked children after clear search and check parent in implicit mode.

---

app/src/docs/_examples/pickerInput/GetRowOptions.example.tsx
uui-components/src/pickers/PickerToggler.tsx
uui-components/src/pickers/hooks/usePicker.ts
uui-components/src/pickers/hooks/usePickerInput.ts
uui/components/pickers/__tests__/PickerInput.test.tsx

- Fixed returning cleared items on body close and click out.
- Fixed disabling enabled rows if some previous row is disabled.

[PickerInput]: Fixed picker input return checked on body close and disabling enabled tags if some previous is disabled.

---

app/src/docs/_examples/tables/EditableTable.example.tsx
uui-docs/src/models/index.ts
uui/components/pickers/PickerInput.tsx

- Added placeholders to EditableTable example
- Fixed editorRef.current.focus on PickerInput.

[EditableTables]: placeholders added.

---

uui-components/src/pickers/hooks/usePickerList.ts
uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/__tests__/useLazyTree.test.ts
uui-core/src/data/processing/views/tree/hooks/strategies/lazyTree/useLazyTree.ts

- Fixed showing picker toggler in LazyDataSource;
- Fixed sorting items before starting loading (handling isUknown).

[PickerList]: Fixed PickerList with LazyDataSource

---

app/src/sandbox/reactQueryLocationsTable/LocationsTable.tsx
app/src/sandbox/reactQueryLocationsTable/useCascadeSelection.ts
uui-components/src/pickers/hooks/usePicker.ts
uui-core/src/data/processing/ArrayDataSource.tsx
uui-core/src/data/processing/AsyncDataSource.tsx
uui-core/src/data/processing/LazyDataSource.tsx
uui-core/src/data/processing/views/__tests__/ArrayListView.test.ts
uui-core/src/data/processing/views/__tests__/AsyncListView.test.ts
uui-core/src/data/processing/views/dataRows/services/useCascadeSelectionService.ts
uui-core/src/data/processing/views/dataRows/services/useCheckingService.ts
uui-core/src/data/processing/views/dataRows/useDataRows.ts

During lazy cascade selection, if some latency was present, during fast checking, previously checked items were rewritten.

[useTree]: Fixed rewriting checked on latency

---

changelog.md
uui-components/src/overlays/Dropdown.tsx

[Tooltip][Dropdown]: fixed recalculation of boundary area(when we shouldn't close body) after target position was changed in `closeOnMouseLeave="boundary"` mode

[Tooltip][Dropdown]: fixed recalculation of boundary area

---

changelog.md
uui-components/src/table/columnsConfigurationModal/__tests__/columnsConfigurationUtils.test.tsx
uui-components/src/table/columnsConfigurationModal/columnsConfigurationUtils.ts
uui-components/src/table/columnsConfigurationModal/hooks/useColumnsConfiguration.ts
uui-core/src/helpers/applyColumnsConfig.ts
uui-core/src/types/tables.ts
uui/components/tables/columnsConfigurationModal/ColumnRow.tsx
uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap

[DataTable]: isAlwaysVisible flag now makes column locked, which means that you can't hide, unpin or reorder this column. Usually applicable for such column without which table because useless.
Note, that isAlwaysVisible column should be always fixed to any side of the table, if you didn't specify `column.fix` prop for such column, 'left' value will be used by default.
Also, if you have a few isAlwaysVisible columns, it's necessary to place it together in the start or end(depends on `fix` prop) of columns array.

* [DataTable]: isAlwaysVisible flag now makes column locked

---

uui/assets/styles/inputs.scss

Fixed tooltip on '+N' `PickerInput` tag in disabled and readonly states.

[inputs]: removed pointer-events: none

---

app/src/docs/_examples/dropdownMenu/Basic.example.tsx
changelog.md
uui/components/overlays/DropdownMenu.tsx

* Fix `offset` for `left-start` placement option. Now it is aligned with `right-start` option
* Set a correct type for `subMenuModifiers` variable and remove a custom in-place interface in `offset` function
* Fix a typo in basic dropdown menu example
Before:
After:

Fix offset in `DropdownSubMenu` for `left-start` option

---

uui-components/src/pickers/hooks/usePicker.ts

Reproduces only if rendered via react-dom render.
Fixed problem with infinite updating of Pickers if onValueChange is called in useEffect.

[Pickers]: fixed infinite updating if onValueChange is called in useEffect.

---

.run/Template Jest.run.xml
app/src/demo/tables/editableTable/columns.tsx
app/src/docs/_examples/tables/EditableTable.example.tsx
app/src/docs/_examples/tables/FiltersPanelBasic.example.tsx
changelog.md
uui-components/src/inputs/DatePicker/Calendar.tsx
uui-components/src/inputs/DatePicker/Day.tsx
uui-components/src/inputs/DatePicker/MonthSelection.tsx
uui-components/src/inputs/DatePicker/YearSelection.tsx
uui-components/src/inputs/DatePicker/calendarConstants.ts
uui-core/src/types/components/TextInput.ts
uui-e2e-tests/framework/fixtures/previewPage/previewPage.ts
uui-e2e-tests/framework/fixtures/previewPage/screenshot.css
uui-e2e-tests/framework/types.ts
uui-e2e-tests/framework/utils/previewTestBuilder.ts
uui-e2e-tests/tests/previewTests/preview.e2e.ts
uui/components/datePickers/Calendar.module.scss
uui/components/datePickers/DatePicker.tsx
uui/components/datePickers/DatePickerBody.module.scss
uui/components/datePickers/RangeDatePicker.tsx
uui/components/datePickers/RangeDatePickerInput.tsx
uui/components/datePickers/__tests__/DatePicker.test.tsx
uui/components/datePickers/__tests__/RangeDatePicker.test.tsx
uui/components/datePickers/__tests__/__snapshots__/Calendar.test.tsx.snap
uui/components/datePickers/__tests__/__snapshots__/DatePickerBody.test.tsx.snap
uui/components/datePickers/__tests__/__snapshots__/RangeDatePicker.test.tsx.snap
uui/components/datePickers/__tests__/__snapshots__/RangeDatePickerBody.test.tsx.snap

Now date picker body receive focus on open and return it back on input after close.

[DatePickers]: improve a11y focus flow behavior

---

changelog.md
uui/components/overlays/DropdownMenu.module.scss
uui/components/overlays/DropdownMenu.tsx

[DropdownMenu]: hover effect is active on the disabled element #2448

---

uui-components/src/pickers/hooks/usePicker.ts

Fixes problem of value synchonization with dataSourceState after change rejection.
Sandbox with reproducible problem: https://codesandbox.io/p/sandbox/uui-forked-ylxhdj

[Pickers]: synchronization of value with internal dataSourceState after value change reject.

---

app/src/common/docs/EditableDocContent.module.scss
app/src/demo/dnd/DndCriterion.module.scss
app/src/demo/dnd/DndMaterial.module.scss
app/src/demo/dnd/DndModule.module.scss
app/src/demo/dnd/DndSection.module.scss
app/src/docs/_examples/dnd/DndMaterial.module.scss
app/src/landing/PatternBlock.module.scss
changelog.md
epam-assets/scss/loveship/typography.scss
epam-assets/theme/theme_6px.scss
epam-assets/theme/theme_electric.scss
epam-assets/theme/theme_loveship.scss
epam-assets/theme/theme_loveship_dark.scss
epam-assets/theme/theme_promo.scss
epam-assets/theme/theme_vanilla_thunder.scss
uui-build/package.json
uui/assets/styles/inputs.scss
uui/components/buttons/LinkButton.module.scss
uui/components/buttons/TabButton.module.scss
uui/components/filters/FilterPanelItemToggler.module.scss
uui/components/inputs/TextArea.module.scss
uui/components/navigation/MainMenu/MainMenuButton.module.scss
uui/components/overlays/DropdownMenu.module.scss
uui/components/overlays/NotificationCard.module.scss
uui/components/pickers/PickerToggler.module.scss
uui/components/widgets/Badge.module.scss
uui/components/widgets/Tag.module.scss
yarn.lock

Sass updated to the last version, warnings 'Mixed Declarations' fixed https://sass-lang.com/documentation/breaking-changes/mixed-decls/

Sass version update

---

uui-components/src/pickers/hooks/usePickerInput.ts
uui-core/src/hooks/useVirtualList/useVirtualList.ts
uui-core/src/hooks/useVirtualList/utils.ts

Fixed https://github.com/epam/UUI/issues/2510
Logging of error for not limited VirtualList parent container was added.
Before, the component was crashing without any error.
Now, the component stops the infinite rows count increasing and logs an error about not limited container height.

[VirtualList]: Added logging of error for not limited VirtualList parent container.

---

app/src/demo/tables/editableTable/columns.tsx
app/src/demo/tables/filteredTable/columns.tsx
app/src/demo/tables/masterDetailedTable/columns.tsx
changelog.md
uui-components/src/table/columnsConfigurationModal/__tests__/columnsConfigurationUtils.test.tsx
uui-components/src/table/columnsConfigurationModal/columnsConfigurationUtils.ts
uui-components/src/table/columnsConfigurationModal/hooks/useColumnsConfiguration.ts
uui-core/src/helpers/applyColumnsConfig.ts
uui-core/src/types/tables.ts
uui/components/tables/columnsConfigurationModal/ColumnRow.tsx
uui/components/tables/columnsConfigurationModal/__tests__/ColumnsConfigurationModal.test.tsx
uui/components/tables/columnsConfigurationModal/__tests__/__snapshots__/ColumnsConfigurationModal.test.tsx.snap

[DataTable]: reworked `isAwaysVisible` column configuration prop and isLocked prop

---

uui/components/buttons/TabButton.module.scss

Hotfix for TabButton caption layout

[TabButton]: fixed layout for caption

---

changelog.md
uui/components/overlays/__tests__/__snapshots__/Modals.test.tsx.snap
uui/settings.ts
uui/settings.types.ts

Fixed value for default modal width

[Modals]: fixed value for default modal width

---

uui-core/src/services/ApiContext.ts
uui-core/src/services/__tests__/ApiContexts.test.ts

Fixes ApiContext handling of request aborts with AbortController. Prior to this fix, aborts during reading and parsing response stalls the requests queue.

Fix Apicontext abort handling

---

changelog.md
uui-components/src/widgets/Clickable.tsx
uui-components/src/widgets/__tests__/Clickable.test.tsx

Fixed issue when `clickAnalyticsEvent` not being sent when `href` prop used at components, that uses inner Clickable component: `Tag`, `Badge`, `Anchor`, `TabButton`, `MainMenuButton`, `Button`, `LinkButton`, `IconButton`.
Closes #2611
Honestly, I don't like the idea to mock entire `React.useContext`, especially when it is required to mock more API than is actually to be tested. There's an option to mock just `jest.spyOn(AnalyticsContext.prototype, 'sendEvent')` in updated test cases instead.

Fix issue when analytics not being sent when `href` prop used

---

app/src/docs/_examples/linkButton/DefaultExample.module.scss
uui/assets/styles/effects.scss
uui/assets/styles/typography.scss
uui/components/buttons/IconButton.module.scss
uui/components/buttons/LinkButton.module.scss
uui/components/buttons/TabButton.module.scss
uui/components/inputs/Switch.module.scss
uui/components/layout/Accordion.module.scss
uui/components/navigation/Anchor.module.scss
uui/components/navigation/MainMenu/Burger/Burger.module.scss
uui/components/navigation/MainMenu/Burger/BurgerButton.module.scss
uui/components/navigation/MainMenu/GlobalMenu.module.scss
uui/components/navigation/MainMenu/MainMenu.module.scss
uui/components/navigation/MainMenu/MainMenuAvatar.module.scss
uui/components/navigation/MainMenu/MainMenuDropdown.module.scss
uui/components/overlays/DropdownMenu.module.scss
uui/components/tables/columnsConfigurationModal/ColumnsConfigurationModal.module.scss
uui/components/widgets/AvatarStack.module.scss
uui/components/widgets/Badge.module.scss

Removed border radius from mixin 'focus-visible-effect', moved to components where it is needed.
Fixed focus cutting off in LinkButton example
see comments in MR #2533

Fixed wrong border radius in focus state for components

---

changelog.md
uui-components/src/pickers/hooks/usePickerInput.ts
uui/components/pickers/__tests__/PickerInput.test.tsx

Need to retest PickerInput list loading behavior, initially selected items load and minCharsToSearch behavior in all cases(Pay attention, that it shouldn't be api calls in network when search length less than minCharsToSearch)

[PickerInput]: fixed unnecessary api calls on body open with `minCharsToSearch` prop and search in body

---

app/src/index.tsx
changelog.md
uui-core/src/services/ErrorContext.ts
uui/components/errors/ErrorPage.module.scss
uui/components/errors/ErrorPage.tsx
uui/components/errors/config.ts
uui/i18n.ts

[ErrorPage]: Added field for additional message with support link (it works with `500, 503, default` errors), added support link for the site
#2588

[ErrorPage]: Added field to provide support link 

---

.github/workflows/base.yml
.github/workflows/dev.yml
.github/workflows/prod.yml
.github/workflows/qa.yml

Update flow to use different artifact registry

Update flow to use different artifact registry

---

changelog.md
uui-components/src/index.scss
uui/components/filters/FilterPanelItemToggler.module.scss

[@epam/uui-components]: fixed invalid global class,
[@epam/uui]: removed invalid pseudo class,
[FilterPanelItemToggler]: removed redundant left padding for postfix.
FilterPanelItemToggler aligned with figma docs - https://www.figma.com/design/qb7WHgBkyBpovFlOZRe30p/UUI-Patterns?node-id=10511-5347&t=xgDWVtaCnRpi4uVT-4

Fixed CSS errors in turbopack mode nextjs

---

changelog.md
test-utils/src/testObjects/PickerModal.ts
uui-components/src/pickers/hooks/types.ts
uui-components/src/pickers/hooks/usePickerModal.ts
uui-core/src/types/pickers.ts
uui/components/pickers/PickerModal.tsx
uui/components/pickers/__tests__/PickerModal.test.tsx
uui/components/pickers/__tests__/__snapshots__/PickerList.test.tsx.snap
uui/components/pickers/__tests__/__snapshots__/PickerModal.test.tsx.snap
uui/i18n.ts

[PickerModal]: fixed `disableClear: true` behavior for `selectionMode: multi`, added `Clear` button functionality to `selectionMode: single`
#2561

[PickerModal]: add clear button functionality and improve its state management

---

changelog.md
uui-components/src/pickers/hooks/usePickerInput.ts
uui/components/overlays/__tests__/Modals.test.tsx

After discussing the results of the [investigation](https://github.com/epam/UUI/issues/2604#issuecomment-2865279088) with @AlekseyManetov, it was decided to use `event.stopPropagation()` to prevent the event's bubbling up to the modal window.
The following changes were made:
* Stop "Escape" key press event propagation in Picker Input component when its body is opened
* Small code improvements in the touched files
#2604

[PickerInput]: `Esc` key unexpectedly closes modal window when Picker Input dropdown is focused and expanded

---

app/src/data/propsOverride_4px.ts
app/src/data/settings_4px.tsx
app/src/docs/_examples/tree/Basic.example.tsx
app/src/docs/_examples/tree/CustomRowExample.example.tsx
app/src/docs/_examples/tree/SimpleNavigation.example.tsx
app/src/docs/pages/components/tree.json
app/src/docs/pages/components/verticalTabButton.json
public/docs/content/tree-CustomRowExample.json
uui-docs/src/peContexts/VerticalTabButtonContext.tsx

Added CustomRowExample, updated VerticalTabButton overrides for 4px theme
#2865, #2853

feat: add CustomRowExample, updated VerticalTabButton overrides for 4px theme
